### Arcface LFW AgeDB CFP-FP evaluation


In [1]:
#from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training, extract_face
import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [3]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\cfp-dataset\\Data\\Images'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\CFP-FP_pairs.txt'

In [4]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathCFP.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\cfp-dataset\\Data\\Images\\001\\frontal\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\04.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\05.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\06.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\07.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\08.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\09.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\10.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\04.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\04.jpg', 'D:\\cfp-

In [5]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [6]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [7]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [8]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsCFP.txt')

In [9]:
print(len(crop))
print(len(message))

7000
7000


In [10]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [11]:
mess=message

In [12]:
print(mess)

[[-0.20975795 -0.31422865  0.9899609  ... -1.0005665   1.6652839
   0.35827792]
 [-0.85788     0.40209806  1.9207904  ... -1.2201699   1.5468774
  -0.67000705]
 [ 0.3197568  -0.3054607   2.4569337  ... -1.0209755   1.4487946
  -0.54525524]
 ...
 [-0.76567423  1.3571008   0.24274501 ... -0.454822    0.04900911
  -0.17586017]
 [ 0.12129052  0.6489141  -0.41557878 ...  0.3081193   1.6559165
  -0.10086884]
 [-1.2653039   0.6110462   1.7767196  ... -0.81409276  0.51278746
   0.3121134 ]]


In [13]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[-0.00822094 -0.01231541  0.03879906 ... -0.03921472  0.06526667
   0.01404181]
 [-0.03790472  0.01776637  0.08486855 ... -0.05391221  0.06834751
  -0.02960371]
 [ 0.01276249 -0.01219189  0.09806386 ... -0.0407503   0.05782589
  -0.02176283]
 ...
 [-0.03770983  0.06683788  0.01195531 ... -0.0224002   0.00241372
  -0.0086612 ]
 [ 0.00489605  0.02619425 -0.01677537 ...  0.01243763  0.0668432
  -0.0040717 ]
 [-0.05516742  0.0266417   0.07746522 ... -0.03549456  0.0223576
   0.01360819]]


In [14]:
mess=np.around(message,5)


In [15]:
print(mess)

[[-0.00822 -0.01232  0.0388  ... -0.03921  0.06527  0.01404]
 [-0.0379   0.01777  0.08487 ... -0.05391  0.06835 -0.0296 ]
 [ 0.01276 -0.01219  0.09806 ... -0.04075  0.05783 -0.02176]
 ...
 [-0.03771  0.06684  0.01196 ... -0.0224   0.00241 -0.00866]
 [ 0.0049   0.02619 -0.01678 ...  0.01244  0.06684 -0.00407]
 [-0.05517  0.02664  0.07747 ... -0.03549  0.02236  0.01361]]


In [16]:
mess=mess*100000

In [17]:
em_dict = dict(zip(crop,mess))

In [18]:
import random
import numpy as np
def genRandom(d,end):
    randNum=[]
    for i in range(0,d):
        b=random.randint(0,end)
        randNum.append(b)
    return np.array(randNum)    


In [19]:
s=genRandom(400,999)
print(s)

[276  46 809 352 979 532 561 492 832 921 678  70 386 196 228 975 650 109
 722 987 772 783 499 599 469 763 825 527 721 388 110 299 899 165 786 175
 883 638 792 966 322 986 202 931 130 290 793 437 563 955 883 862 942  47
 157 807 941 198 740 269 458 247 627 833 758 982 486 960 335 876 249 245
 482  24 475 948 264 338 616 519 272 973  13 125  40 233 848 929 814 617
 995 876 346  96 872  50 771 636 163 888 762 360 308   1 240 115 536 890
 705 607 638 670 532 642 367 948 703 588 906 142 828 297 247 209 723 538
 268 179 375 707 374 435 301 860 800 942 968  59 983 281  25 834 574 871
 831  67 701 458 281 304 600 303  40 699 688 497 113 134  27 725 730 192
 266 756 436 826 922 180 510 838 735 657 254 611 569 576 355 257 350 862
 540 253 632 937 770 398 193 628 350 632 999 493 413 618 553 276 203  64
 103 248 529 471 974 244 555 175 266 157 896 387 598 612 137 726 830 402
 862 366  47 603 204 646 679 516 623 503 993 485 265  69 159 569 595 597
 686  38 178 949 517 313 503 305 244 701 449 906 97

In [20]:
import hashlib
import time
# 要测量的代码
def sha256_string(input_string):
    # 将字符串编码为 UTF-8 字节
    encoded_string = input_string.encode('utf-8')
    # 创建 SHA-256 哈希对象
    sha256_hash = hashlib.sha256(encoded_string)
    # 获取十六进制格式的哈希值
    return sha256_hash.digest()



 
# 示例
text = "Hello, World!"

start = time.perf_counter()
hashed_text = sha256_string(text)

 
end = time.perf_counter()
elapsed = end - start

print(f"SHA-256 哈希值: {hashed_text}")
# 计算耗时（秒）
print(f"代码执行耗时: {elapsed:.9f} 秒")


SHA-256 哈希值: b'\xdf\xfd`!\xbb+\xd5\xb0\xafgb\x90\x80\x9e\xc3\xa51\x91\xdd\x81\xc7\xf7\nK(h\x8a6!\x82\x98o'
代码执行耗时: 0.000040000 秒


In [21]:
#离散的hash阈值比较方法

import numpy as np
def hashComare(dist,p,q,y):
    
    #q=1024*1024  #明文模数
    print("q:")
    print(q)
    threshold=2000
    rightMax=10000
    #y表示向量保留多少位小数，保留的小数越多最后化成整数的区间越大
    factor=pow(10,y-2)
    threshold=threshold*factor*factor
    rightMax=rightMax*factor*factor
    p=p*factor*factor
    threshold=int(threshold)
    rightMax=int(rightMax)
    p=int(p)
    
    
    
    # 生成 10 个 [0, 10000) 的随机整数
    #dist = np.random.randint(0, 10000, size=10000)
    print("dist:")
    print(dist)
    #p=1
    dimension=dist.shape[0]
    TrueAns=[]
    for i in range(dimension):
        isContains=False
        if (dist[i] > threshold) and (dist[i] <= rightMax):
            isContains=True
        TrueAns.append(isContains)    
    r=genRandom(dimension,int(pow(10,20)-1))
    print("r:")
    print(r)
    dist=dist+r
    dist=dist%q
    dist=dist//p
    dist=dist%q
    print("(((dist+r)%q)/p)%q:")
    print(dist)
    #     print(dist[:5])




    # 生成维度为4000的ndarray，所有值都是constant_value  

    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh%q
    thresh=thresh//p
    thresh=thresh%q
    print("(((threshold+r)%q)/p)%q:")
    print(thresh)



    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM%q
    rightM=rightM//p
    rightM=rightM%q
    print("(((rightM+r)%q)/p)%q:")
    print(rightM)
    ans=[]
    for i in range(dimension):  # 0 到 4
        #print(i)
        left=thresh[i]
        right=rightM[i]
        sim=dist[i]
        #print(left)
        #print(right)
        #print(sim)
       #转换为字符串（默认）
        str_sim = "{}".format(sim)
        #print(str_sim) 
        simHash=sha256_string(str_sim)
        #print(simHash)
        # 组合两个条件：dist > thresh 且 dist <= rightM
        start = left+1  # 起始数字
        count = (rightMax-threshold)//p  # 往后数 right-left 个数（包括起始数字）
        Hashs=[]
        for i in range(start, start + count):
            num=i%q
            str_num= "{}".format(num)
            SetHash=sha256_string(str_num)
            Hashs.append(SetHash)
            #print(i)
        #print(Hashs)
        isContain=False
        for i in range(count):
            if simHash==Hashs[i]:
                isContain=True
        ans.append(isContain)   
    print(TrueAns)
    print(ans)

    sameCount=0
    diffCount=0
    for i in range(dimension):
        if TrueAns[i]==ans[i]:
            sameCount=sameCount+1
        else:
            diffCount=diffCount+1


    print("相同结果的数量:", sameCount) 

    print("不同结果的数量:", diffCount)  
    return ans

In [22]:
p=100
q=1024*1024
dist = np.random.randint(-10000, 10000, size=1000)
y=2
predict_issame=hashComare(dist,p,q,y)
print(predict_issame)

q:
1048576
dist:
[-4222  6405 -9136  9640 -2548 -1946  9403  -300  2839 -7514 -3078  2516
  5117   760 -3745  1025   245 -8668 -5649  4570 -8702  3470 -9479 -6638
  5629  3283  4983   305 -9260  3564 -4482  2943  2741  3953 -6771  1134
 -7569 -7704  5729 -1035 -9354  -471 -1159  9334 -2097 -6750  4718  -199
  -336 -3649 -8396 -2115 -7736  6011 -4083  9155  3809 -5539 -8030  5013
  9345   976 -4878 -2010 -8361 -4087   545  8185 -4778 -3401  3024 -7990
 -3833  4431  7530 -2003 -7474  1917 -9547  9036 -1302 -8158 -5186  6684
 -9667  8806 -3730  4303 -9505  7018 -3554 -2863  6397  1964  4516 -1018
 -8359  6851  7099 -2825 -9068 -1263 -9150 -2982  9550   131 -1018   437
  8093  2927 -1666 -1856  -155 -5610 -6048 -4974  8899   569 -5861 -3122
 -6829 -5178 -3832   806 -1749  3387  5604  3993 -8754  -155 -8278  2525
 -4413 -1965 -8813  4583   974 -7738 -1989 -5282 -9264 -2081  3022 -3152
   529 -7628  -855 -6798 -6185  3814  2410  9015  1249 -5181 -5650  1183
 -6363 -5227  8721  1614  7907 -35

In [44]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  
y=5
p=2000
q=pow(2,58)
thresh=2000

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):

    dist = np.round(dist).astype(np.int64) #注意前半部分在同态下算完应该是整数  浮点数转为整数
    
    
    
    predict_issame=hashComare(dist,p,q,y)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
       # threshold=4000
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    #threshold=0.41
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    #thresholds = np.arange(-10000, 10000, 5000) 
    factor=pow(10,y-2)
    thresholds=[int(thresh*factor*factor)]
    #thresholds = np.arange(-40000, 40000, 100) 
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 5000)
    thresholds=[int(thresh*factor*factor)]
    #thresholds = np.arange(-1, 1, 0.001)
    #thresholds = np.arange(-40000, 40000,10)
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
#             path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
#             path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            path0 = add_extension(os.path.join(lfw_dir, pair[1]))
            path1 = add_extension(os.path.join(lfw_dir, pair[2]))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[1]))
            path1 = add_extension(os.path.join(lfw_dir, pair[3]))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [45]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(14000, 512)
q:
288230376151711744
dist:
[6603305045 5666991835 5136424563 ... -535621490 1106565969 1285814633]
r:
[28717634898172474492 85376612959627999819 25142289901983525873 ...
 43076708859489825853 11882660295729675747 88412268662177713506]
(((dist+r)%q)/p)%q:
[91413832 30210812 33123590 ... 65191406 32607437 106886780]
(((threshold+r)%q)/p)%q:
[91413830 30210810 33123589 ... 65191407 32607437 106886780]
(((rightM+r)%q)/p)%q:
[91413834 30210814 33123593 ... 65191411 32607441 106886784]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,

q:
288230376151711744
dist:
[3328977630 4351119208 2491641030 ... -535621490 1106565969 1285814633]
r:
[99357381154532963980 74808733005944317901 78027962460118536490 ...
 82872823558054462537 32808315682826621624 4803494505771719230]
(((dist+r)%q)/p)%q:
[103065880 78532793 102880450 ... 75352800 119141589 95904244]
(((threshold+r)%q)/p)%q:
[103065880 78532792 102880450 ... 75352802 119141589 95904244]
(((rightM+r)%q)/p)%q:
[103065884 78532796 102880454 ... 75352806 119141593 95904248]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, T

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

2000000000
q:
288230376151711744
dist:
[ 6014825425  3355526292  5285763606  5321169922  3632859656  4297801910
  5863475268  5008124086  5695749200  4739861236  6021470147  5702456309
  5153807131  5689254222  4349994954  4459280239  4439899475  4062471775
  3526138843  4178449108  4911060773  4073785899  2473875373  5801952694
  2021805117  3314643847  4354882760  4056249866  5093639750  3661416040
  4497806762  3279222538  3881937751  3884841501  3574278388  4372246652
  5344737436  5558929401  4478913275  4546482576  4414787263  3257069983
  4527201339  4952133787  5311444631  5577169712  2797273840  5380256623
  3074810788  5208918669  6791915849  6059053141  5999710105  5414769871
  6395196868  5907127480  5533612326  4089992707  3429121011  2921673657
  3687731691  3154372346  6004704348  5861733937  5359285396  5687623882
  6352106613  6603205977  5013888997  5330792079  5621857127  5344952256
  5727039136  5270070066  4346134261  5304001897  6265832983  3599308658
  4157582236

q:
288230376151711744
dist:
[3328977630 4351119208 2491641030 ... -535621490 1106565969 1285814633]
r:
[22017001891755965230 52282306360220152091 82874571037687506106 ...
 81723668705693320235 44463843122287798270 99535748031729178479]
(((dist+r)%q)/p)%q:
[55746653 56304140 76226542 ... 77236127 38182598 48134130]
(((threshold+r)%q)/p)%q:
[55746653 56304139 76226542 ... 77236128 38182598 48134130]
(((rightM+r)%q)/p)%q:
[55746657 56304143 76226546 ... 77236132 38182602 48134134]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

q:
288230376151711744
dist:
[3328977630 4351119208 2491641030 ... -535621490 1106565969 1285814633]
r:
[49035080778009617146 74619234099138723157 50659366280699593630 ...
 3804638728800488311 64852593364906551923 85201901806599835677]
(((dist+r)%q)/p)%q:
[17958417 127898528 109525228 ... 28821919 379365 86970421]
(((threshold+r)%q)/p)%q:
[17958417 127898526 109525228 ... 28821920 379366 86970421]
(((rightM+r)%q)/p)%q:
[17958421 127898530 109525232 ... 28821924 379370 86970425]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

2000000000
q:
288230376151711744
dist:
[ 4362599361  5713260167  5300719383  5849871721  6712742119  4974626172
  4163368957  5253668395  3804641237  4741158995  5110641910  4839973046
  4969659438  4089235622  5783598926  5873329444  5586424358  5780273376
  6465902518  6112569978  6005405107  6260947347  4763802850  5544603828
  4445455890  5554049843  5692986782  5002253438  6085256947  5155619968
  5245697200  5005610947  5288333909  5353814065  6124617818  3539292408
   930452101  3470697356  5225058004  5157427068  4779072058  3798556347
  1262797791   885636005  4325072184  5101513527   892796425  6224322082
  4727487243  5472882004  3897458348  5408319679  5649235310  4703031315
  4812856688  4705241065  6397063475  6208238851  5814850504  5749564945
  5786409558  6780079533  6301754611  5207870854  5480725459  6302761537
  5651815605  5438149693  6893593821  6617928940  5782008993  7052165135
  5609051704  6241013642  6269141718  6706126486  5870670668  3987229422
  1468890515

In [46]:
print(accuracy)
np.mean(accuracy)







[0.96142857 0.96428571 0.98142857 0.96714286 0.97       0.96571429
 0.96714286 0.97714286 0.97714286 0.95428571]


0.9685714285714285

In [237]:
np.mean(all_threshold)


D:\MiniConda\envs\jucing\lib\site-packages\numpy\core\fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
D:\MiniConda\envs\jucing\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [92]:
print(len(pairs))

6000


In [1025]:
    #a little test for look the error situation
    dist = np.array([2100,2200.2299,2500, 3000, 4000,5000,9000,10000])
    p=1000
    dimension=dist.shape[0]
    r=genRandom(dimension,99999999)
    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[55633634 45308601 12542928 70346752  9871909 11995441 77442695 64250201]
[55635. 45310. 12545. 70349.  9875. 12000. 77451. 64260.]
[55635 45310 12545 70349  9874 11997 77444 64252]
[55643 45318 12552 70356  9881 12005 77452 64260]
[False False False False  True  True  True  True]
