### Arcface LFW AgeDB CFP-FP evaluation


In [1]:
#from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training, extract_face
import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [2]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\lfw'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\LFW_pairs.txt'

In [3]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathLFW.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\lfw\\Aaron_Eckhart\\Aaron_Eckhart_0001.jpg', 'D:\\lfw\\Aaron_Guiel\\Aaron_Guiel_0001.jpg', 'D:\\lfw\\Aaron_Patterson\\Aaron_Patterson_0001.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0001.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0002.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0003.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0004.jpg', 'D:\\lfw\\Aaron_Pena\\Aaron_Pena_0001.jpg', 'D:\\lfw\\Aaron_Sorkin\\Aaron_Sorkin_0001.jpg', 'D:\\lfw\\Aaron_Sorkin\\Aaron_Sorkin_0002.jpg', 'D:\\lfw\\Aaron_Tippin\\Aaron_Tippin_0001.jpg', 'D:\\lfw\\Abbas_Kiarostami\\Abbas_Kiarostami_0001.jpg', 'D:\\lfw\\Abba_Eban\\Abba_Eban_0001.jpg', 'D:\\lfw\\Abdel_Aziz_Al-Hakim\\Abdel_Aziz_Al-Hakim_0001.jpg', 'D:\\lfw\\Abdel_Madi_Shabneh\\Abdel_Madi_Shabneh_0001.jpg', 'D:\\lfw\\Abdel_Nasser_Assidi\\Abdel_Nasser_Assidi_0001.jpg', 'D:\\lfw\\Abdel_Nasser_Assidi\\Abdel_Nasser_Assidi_0002.jpg', 'D:\\lfw\\Abdoulaye_Wade\\Abdoulaye_Wade_0001.jpg', 'D:\\lfw\\Abdoulaye_Wade\\Abdoulaye_Wade_0002.jpg', 'D:\\lfw\\Abd

In [4]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [5]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [6]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [7]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsLFW.txt')

In [8]:
print(len(crop))
print(len(message))

13233
13233


In [9]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [10]:
mess=message

In [11]:
print(mess)

[[ 1.1628096  -0.85084873  1.2422147  ... -0.98252064 -0.69344217
  -1.0288785 ]
 [-0.23853248 -1.2733148  -0.42157245 ... -0.05360752 -0.38319495
   0.6318322 ]
 [ 0.7250262   0.02286638 -1.1436646  ...  0.6627271   1.6255715
   0.8349597 ]
 ...
 [-1.1354966   0.2686497  -0.38320267 ...  0.50229514  0.836322
   1.4965911 ]
 [-0.504686    1.0311847  -0.8311979  ... -2.7869985  -1.9792159
   1.271286  ]
 [-1.7138352   1.3578902  -0.3757491  ...  2.2136726   1.7626736
   1.675812  ]]


In [12]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[ 0.05194577 -0.03800966  0.05549301 ... -0.04389179 -0.03097789
  -0.04596271]
 [-0.01037856 -0.05540198 -0.01834263 ... -0.00233247 -0.01667283
   0.02749104]
 [ 0.03016753  0.00095144 -0.04758661 ...  0.02757534  0.06763822
   0.03474174]
 ...
 [-0.0491417   0.01162654 -0.01658414 ...  0.02173818  0.0361941
   0.06476904]
 [-0.02269937  0.04637981 -0.03738496 ... -0.12535143 -0.08901961
   0.0571789 ]
 [-0.07017887  0.05560349 -0.01538634 ...  0.09064644  0.07217873
   0.06862188]]


In [13]:
mess=np.around(message,5)


In [14]:
print(mess)

[[ 0.05195 -0.03801  0.05549 ... -0.04389 -0.03098 -0.04596]
 [-0.01038 -0.0554  -0.01834 ... -0.00233 -0.01667  0.02749]
 [ 0.03017  0.00095 -0.04759 ...  0.02758  0.06764  0.03474]
 ...
 [-0.04914  0.01163 -0.01658 ...  0.02174  0.03619  0.06477]
 [-0.0227   0.04638 -0.03738 ... -0.12535 -0.08902  0.05718]
 [-0.07018  0.0556  -0.01539 ...  0.09065  0.07218  0.06862]]


In [15]:
mess=mess*100000

In [16]:
em_dict = dict(zip(crop,mess))

In [17]:
import random
import numpy as np
def genRandom(d,end):
    randNum=[]
    for i in range(0,d):
        b=random.randint(0,end)
        randNum.append(b)
    return np.array(randNum)    


In [18]:
s=genRandom(400,999)
print(s)

[ 49  36 646 877 175  79  69 671 693 784 718 841 227 101 108 784 782 669
 455 423 947  45 884  16 901 230 347 477 963 144 368  73 501 419 105  85
 876 548 768 900 996 231 214 106 922 806 434 285 326 207 938 214 726 290
 660 830 561 933 483   2 611 666 550 597 306 609 863 324 198 126 290 327
 635 753 542 328 722 690 477 162 149 412 853 959 266 365 180 767  91 125
 151  51 214 882 221 970 395 160 953 839 736 353 814 444 413  32 724 314
 779 597 287 936 877 441 379 902 498 263 928 398 898 701 837 999 571 564
  44 121 515 356 422 227 117 643  33 780  95  24 865 434 553 953 158 960
 383 597 805 123 366 665 613 700 112 165 634 641 338 905 331 212 912 835
 882 236  25 547  40 945 369 811 560 928 209 598 307 178 900 667 116 193
 983 869 522  60 800 382 432 488 898 534 876  20 347 702 529   3 807 531
 218 992  71 296  16 972 638 199 191 404 758 171 951 887 566 606 120 545
 826 856 422 704 851 945 519 362 966 439 226 236 889 917 606 736  85 499
 437  18  67 546 635 492 397 421 240 171 634 609 66

In [19]:
import hashlib
import time
# 要测量的代码
def sha256_string(input_string):
    # 将字符串编码为 UTF-8 字节
    encoded_string = input_string.encode('utf-8')
    # 创建 SHA-256 哈希对象
    sha256_hash = hashlib.sha256(encoded_string)
    # 获取十六进制格式的哈希值
    return sha256_hash.digest()



 
# 示例
text = "Hello, World!"

start = time.perf_counter()
hashed_text = sha256_string(text)

 
end = time.perf_counter()
elapsed = end - start

print(f"SHA-256 哈希值: {hashed_text}")
# 计算耗时（秒）
print(f"代码执行耗时: {elapsed:.9f} 秒")


SHA-256 哈希值: b'\xdf\xfd`!\xbb+\xd5\xb0\xafgb\x90\x80\x9e\xc3\xa51\x91\xdd\x81\xc7\xf7\nK(h\x8a6!\x82\x98o'
代码执行耗时: 0.000037400 秒


In [22]:
#离散的hash阈值比较方法
import secrets
import numpy as np
def hashComare(dist,p,q,y):
    
    #q=1024*1024  #明文模数
    print("q:")
    print(q)
    threshold=2000
    rightMax=10000
    #y表示向量保留多少位小数，保留的小数越多最后化成整数的区间越大
    factor=pow(10,y-2)
    threshold=threshold*factor*factor
    rightMax=rightMax*factor*factor
    p=p*factor*factor
    threshold=int(threshold)
    rightMax=int(rightMax)
    p=int(p)
    
    
    
    # 生成 10 个 [0, 10000) 的随机整数
    #dist = np.random.randint(0, 10000, size=10000)
    print("dist:")
    print(dist)
    #p=1
    dimension=dist.shape[0]
    TrueAns=[]
    for i in range(dimension):
        isContains=False
        if (dist[i] > threshold) and (dist[i] <= rightMax):
            isContains=True
        TrueAns.append(isContains)    
        
    r=genRandom(dimension,int(pow(10,20)-1)) #[0,10^17-1]
    print("r:")
    print(r)
    dist=dist+r
    dist=dist%q
    dist=dist//p
    dist=dist%q
    print("(((dist+r)%q)/p)%q:")
    print(dist)
    #     print(dist[:5])




    # 生成维度为4000的ndarray，所有值都是constant_value  

    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh%q
    thresh=thresh//p
    thresh=thresh%q
    print("(((threshold+r)%q)/p)%q:")
    print(thresh)



    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM%q
    rightM=rightM//p
    rightM=rightM%q
    print("(((rightM+r)%q)/p)%q:")
    print(rightM)
    ans=[]
    for i in range(dimension):  # 0 到 4
        #print(i)
        left=thresh[i]
        right=rightM[i]
        sim=dist[i]
        #print(left)
        #print(right)
        #print(sim)
       #转换为字符串（默认）
        str_sim = "{}".format(sim)
        #print(str_sim) 
        simHash=sha256_string(str_sim)
        #print(simHash)
        # 组合两个条件：dist > thresh 且 dist <= rightM
        start = left+1  # 起始数字
        count = (rightMax-threshold)//p  # 往后数 right-left 个数（包括起始数字）
        Hashs=[]
        for i in range(start, start + count):
            num=i%q
            str_num= "{}".format(num)
            SetHash=sha256_string(str_num)
            Hashs.append(SetHash)
            #print(i)
        #print(Hashs)
        isContain=False
        for i in range(count):
            if simHash==Hashs[i]:
                isContain=True
        ans.append(isContain)   
    print(TrueAns)
    print(ans)

    sameCount=0
    diffCount=0
    for i in range(dimension):
        if TrueAns[i]==ans[i]:
            sameCount=sameCount+1
        else:
            diffCount=diffCount+1


    print("相同结果的数量:", sameCount) 

    print("不同结果的数量:", diffCount)  
    return ans

In [23]:
p=100
q=1024*1024
dist = np.random.randint(-10000, 10000, size=1000)
y=2
predict_issame=hashComare(dist,p,q,y)
print(predict_issame)

q:
1048576
dist:
[ 5744   373 -4649  1062 -8799  8774 -3371  3662 -6359  3483 -9219 -8745
  7761  7376 -4363  8029  1451  6255  7949  9402    84 -3683 -4536 -2653
 -2296 -2513  3000 -6508 -5793  -582 -8340 -2437 -3258  1607  1825  5670
 -9714 -3650  6845  7199 -7913  2309 -2027  4544  6322  9671 -8634  8596
 -9118 -9323 -6821 -7643 -6682  4115  -584  8772 -8985 -9463 -5649 -9862
 -8127  5011  6972  3512 -6589  5576 -9295 -5606  3570 -6835  7442  1953
 -6709  -139   226  7730   134 -3719 -4632   814  5378  9552  7486 -5790
  9536 -6587 -4577 -8648  3246 -8898 -5500  4254 -2403   919 -9560 -8731
  5076 -3487 -7378 -3008 -2053 -4516  -610 -7393  7114  5947  2247 -4196
  1105 -9306  9028 -9876  2801 -5291   478  1252  7420  4422  9636  7734
   333  7448  1380 -1399  6207  8238  1685  2082 -3595  1637   392 -9039
  3062  4772 -7704  4430 -7107   561  2905 -3839 -3586  -587 -7176 -5649
  6796 -8336 -5727 -1086  8839 -1089  2466 -3039 -7088 -4391 -1321  3549
  1878  7971 -9451 -2295  8978 -98

In [48]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  
y=5
q=pow(2,58)
p=4000

thresh=2000

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):

    dist = np.round(dist).astype(np.int64) #注意前半部分在同态下算完应该是整数  浮点数转为整数
    
    
    
    #q=1024597500
    predict_issame=hashComare(dist,p,q,y)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
       # threshold=4000
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    #threshold=0.41
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    #thresholds = np.arange(-10000, 10000, 5000) 
    factor=pow(10,y-2)
    thresholds=[int(thresh*factor*factor)]
    #thresholds = np.arange(-40000, 40000, 100) 
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 5000)
    thresholds=[int(thresh*factor*factor)]
    #thresholds = np.arange(-1, 1, 0.001)
    #thresholds = np.arange(-40000, 40000,10)
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path+'.jpg'

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[2], pair[2] + '_' + '%04d' % int(pair[3])))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [46]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(12000, 512)
q:
288230376151711744
dist:
[7245435546 7236557467 7693563928 ...  135085554  970908249 -425722747]
r:
[70738642642923814785 4565848108682715400 60252258201913245064 ...
 23254411932675384960 76727818892168940086 21996650199479216973]
(((dist+r)%q)/p)%q:
[61100246 121196236 6054796 ... 97990920 29269418 45570805]
(((threshold+r)%q)/p)%q:
[61100243 121196234 6054794 ... 97990921 29269418 45570806]
(((rightM+r)%q)/p)%q:
[61100247 121196238 6054798 ... 97990925 29269422 45570810]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

q:
288230376151711744
dist:
[7241888096 8302594743 8037246293 ...  135085554  970908249 -425722747]
r:
[68901724516965840791 17044874407857641142 95506075862658594421 ...
 70171155628286704544 33365164721765263049 33199855325247724280]
(((dist+r)%q)/p)%q:
[7332311 19641111 50910682 ... 65587111 109335732 26681033]
(((threshold+r)%q)/p)%q:
[7332309 19641108 50910679 ... 65587112 109335733 26681034]
(((rightM+r)%q)/p)%q:
[7332313 19641112 50910683 ... 65587116 109335737 26681038]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

dist:
[7241888096 8302594743 8037246293 ...  135085554  970908249 -425722747]
r:
[74297630246518213035 6263216861852026674 53761575341253896082 ...
 28607843340590258746 16273894922978612673 54217453027827674488]
(((dist+r)%q)/p)%q:
[111211791 105189485 75362692 ... 36518050 66496929 15071155]
(((threshold+r)%q)/p)%q:
[111211788 105189482 75362689 ... 36518051 66496930 15071156]
(((rightM+r)%q)/p)%q:
[111211792 105189486 75362693 ... 36518055 66496934 15071160]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

相同结果的数量: 5387
不同结果的数量: 13
2000000000
q:
288230376151711744
dist:
[ 6838960429  6316723192  6195418032  7908033136  6859311688  7263193817
  7119761543  7553212165  7006073138  6651349415  6943440919  5719604751
  7489128917  7258176171  4907860703  6190624786  6637308557  5871601389
  4477992370  5906598311  6440309206  8189426693  5948672386  6055600036
  5630978563  6722259143  5980539535  5793784063  5888963060  6864811387
  6800098115  7457623382  7162763882  4583434621  5097400063  8194935338
  5883068287  4010454196  4607487233  5929575315  6667117230  6428095834
  7190753941  5468519717  5888733798  6269275153  6938401102  7196022529
  7508188357  6703896451  8149626791  7155400028  7051475219  7242705249
  6814872420  7155389663  6892629799  7761141112  7577920040  5809964515
  5872492928  5850746072  7576340292  4792556806  5811026687  6933105379
  8286913440  5407126500  6233113845  5902783695  8084144275  6835536403
  7378210403  7449074996  8508939095  7133344596  659257398

2000000000
q:
288230376151711744
dist:
[ 5562358461  6511034199  6687063694  7947479432  7564765287  8088007548
  6400007913  7474272962  6555759608  7344006011  7281215931  5797958348
  5748485447  4801411397  8244246783  6448469990  6072838563  5859380943
  7844833893  6774172755  6437679550  6251896408  8338385018  5733075038
  6777686844  5996104248  7255502539  6217890957  5371211530  7513849081
  5917981619  7008720349  8136040562  8027106139  7295986129  6571990051
  7331258292  7241742665  7343178352  7733329251  7126791495  7704759724
  8313261053  7691941638  7545141677  6300453499  7125774799  6734053710
  6630877363  7343618706  7522856601  6167503429  8241319312  7084234710
  6544871396  6771823677  7803707359  5358149060  5595144550  5840918871
  5932328265  5811471849  6386437015  7410889076  7400691131  6200608731
  7572170077  6571333904  5565213577  7051614575  6039462484  5166190581
  6565353318  5844957603  6563560524  5970308712  7003822818  6342193110
  7248854382

r:
[91335845062625924069 23232798427667236966 42944860991999127676
 26535756124560096799 36110444635822100995 32455244013133699375
 3963914112221235136 70177564637050148289 79928364996174208651
 62776450190451141097 64876297482940279155 65479497333800950877
 13843919612081844167 29221409495926591860 99520589225061832232
 97813919598493978671 71570917633338919387 10022023459866467761
 2422556061114079937 83683298288487036676 80879491527037005147
 56254059126764204213 49264458390388844800 13306147775364979049
 43580312993584356499 45917077273223704603 5345486009618983521
 90823788825133757286 55323149425056306303 53490349002386904822
 44194245571602216437 72776309277682836926 51723637056693427972
 24644606447127778363 16188912660486043868 76963798177711164049
 65081684558458259433 4802693551975559287 70028352343458442254
 87626170169439414258 79421274859397790497 72720588014589001500
 3150288699901323900 72447030636989643845 27094213175340677167
 61769135436863177388 90384301837493068712

r:
[10007014049241843901 21156756812518413861 84080920409222093303 ...
 31780163702132082297 56104995168085085899 39881606088384637306]
(((dist+r)%q)/p)%q:
[103590633 57969680 102940478 ... 37411162 94151097 52907089]
(((threshold+r)%q)/p)%q:
[103590631 57969677 102940475 ... 37411163 94151098 52907090]
(((rightM+r)%q)/p)%q:
[103590635 57969681 102940479 ... 37411167 94151102 52907094]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True

In [47]:
print(accuracy)
np.mean(accuracy)







[0.995      0.99666667 1.         0.99833333 0.99166667 1.
 0.99333333 1.         1.         1.        ]


0.9974999999999999

In [237]:
np.mean(all_threshold)


D:\MiniConda\envs\jucing\lib\site-packages\numpy\core\fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
D:\MiniConda\envs\jucing\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [92]:
print(len(pairs))

6000


In [45]:
    #a little test for look the error situation
    dist = np.array([2100,2200,2299,2500, 3000, 4000,5000,9000,10000])
    p=1
    dimension=dist.shape[0]
    r=genRandom(dimension,9999999999999)

    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[ 951465536158  415304871200 8412959936486  114860805330 8437075564886
 1141522687973 5032691210173 1404208877694 5033886800890]
[ 951465538258  415304873400 8412959938785  114860807830 8437075567886
 1141522691973 5032691215173 1404208886694 5033886810890]
[ 951465538458  415304873500 8412959938786  114860807630 8437075567186
 1141522690273 5032691212473 1404208879994 5033886803190]
[ 951465546158  415304881200 8412959946486  114860815330 8437075574886
 1141522697973 5032691220173 1404208887694 5033886810890]
[False False False  True  True  True  True  True  True]
