### Arcface LFW AgeDB CFP-FP evaluation


In [1]:
# import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [2]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\cfp-dataset\\Data\\Images'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\CFP-FP_pairs.txt'

In [3]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathCFP.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\cfp-dataset\\Data\\Images\\001\\frontal\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\04.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\05.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\06.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\07.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\08.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\09.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\10.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\04.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\04.jpg', 'D:\\cfp-

In [4]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [5]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [6]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [7]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsCFP.txt')

In [8]:
print(len(crop))
print(len(message))

7000
7000


In [9]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [10]:
mess=message

In [11]:
print(mess)

[[-0.20975795 -0.31422865  0.9899609  ... -1.0005665   1.6652839
   0.35827792]
 [-0.85788     0.40209806  1.9207904  ... -1.2201699   1.5468774
  -0.67000705]
 [ 0.3197568  -0.3054607   2.4569337  ... -1.0209755   1.4487946
  -0.54525524]
 ...
 [-0.76567423  1.3571008   0.24274501 ... -0.454822    0.04900911
  -0.17586017]
 [ 0.12129052  0.6489141  -0.41557878 ...  0.3081193   1.6559165
  -0.10086884]
 [-1.2653039   0.6110462   1.7767196  ... -0.81409276  0.51278746
   0.3121134 ]]


In [12]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[-0.00822094 -0.01231541  0.03879906 ... -0.03921472  0.06526667
   0.01404181]
 [-0.03790472  0.01776637  0.08486855 ... -0.05391221  0.06834751
  -0.02960371]
 [ 0.01276249 -0.01219189  0.09806386 ... -0.0407503   0.05782589
  -0.02176283]
 ...
 [-0.03770983  0.06683788  0.01195531 ... -0.0224002   0.00241372
  -0.0086612 ]
 [ 0.00489605  0.02619425 -0.01677537 ...  0.01243763  0.0668432
  -0.0040717 ]
 [-0.05516742  0.0266417   0.07746522 ... -0.03549456  0.0223576
   0.01360819]]


In [13]:
mess=np.around(message,2)


In [14]:
print(mess)

[[-0.01 -0.01  0.04 ... -0.04  0.07  0.01]
 [-0.04  0.02  0.08 ... -0.05  0.07 -0.03]
 [ 0.01 -0.01  0.1  ... -0.04  0.06 -0.02]
 ...
 [-0.04  0.07  0.01 ... -0.02  0.   -0.01]
 [ 0.    0.03 -0.02 ...  0.01  0.07 -0.  ]
 [-0.06  0.03  0.08 ... -0.04  0.02  0.01]]


In [15]:
mess=mess*100

In [16]:
em_dict = dict(zip(crop,mess))

In [17]:
import random
import numpy as np
def genRandom(d,end):
    randNum=[]
    for i in range(0,d):
        b=random.randint(0,end)
        randNum.append(b)
    return np.array(randNum)    


In [18]:
s=genRandom(400,999)
print(s)

[843 329 661 124 809  49 183  65 737 652 801 974 745 830 736 369 499 276
 618 463 587 785 144 422 874 544 124 929 893 505 743 445 412 792 414 722
  42 390 869 448 628 993 407 740 243 230 329 441 367 374 961 451 660 512
  81 496 354 195 245 723 322 411 403 350 186 754 713 623  79 438 457 519
 444 201  15 838 154 944 734 646 721 609 831 676 341 933 749 537 727 228
 318 716 904 264 242 654 345 513  96 692 859 221  37 952 656 851 816 642
 513 709 489  50 216 267 532 289 332 433 899 128 377 245 482 953 970 367
 117 328 953  93 721 585 206 701 639 729 255 375 299 984 905  56 128 963
 711 681 605 550 554 684 981 126 557 411 932 700 494 520 258 773 459 195
 774 419 928 318 282 947 103 318 155 217 767 179 724 213   7 751 487 833
 694 920 899 543 978 902 635 898 274 978 590  76  61 642 546 736  11 764
 437 254 547 509 246 799 684 690 444  92 274 808 911 697 339 667  14 908
 191 108 643 746 710 369 446 550 752 708 871 623 437 653 307  93 386 791
 290 672 412 911  43 300 636 169 125 503 374 382 56

In [19]:
import hashlib
import time
# 要测量的代码
def sha256_string(input_string):
    # 将字符串编码为 UTF-8 字节
    encoded_string = input_string.encode('utf-8')
    # 创建 SHA-256 哈希对象
    sha256_hash = hashlib.sha256(encoded_string)
    # 获取十六进制格式的哈希值
    return sha256_hash.hexdigest()



 
# 示例
text = "Hello, World!"

start = time.perf_counter()
hashed_text = sha256_string(text)

 
end = time.perf_counter()
elapsed = end - start

print(f"SHA-256 哈希值: {hashed_text}")
# 计算耗时（秒）
print(f"代码执行耗时: {elapsed:.9f} 秒")


SHA-256 哈希值: dffd6021bb2bd5b0af676290809ec3a53191dd81c7f70a4b28688a362182986f
代码执行耗时: 0.000042100 秒


In [20]:
#离散的hash阈值比较方法

import numpy as np
def hashComare(dist,p,q):
    #q=1024*1024  #明文模数
    print("q:")
    print(q)
    threshold=2000
    rightMax=10000
    # 生成 10 个 [0, 10000) 的随机整数
    #dist = np.random.randint(0, 10000, size=10000)
    print("dist:")
    print(dist)
    #p=1
    dimension=dist.shape[0]
    TrueAns=[]
    for i in range(dimension):
        isContains=False
        if (dist[i] > threshold) and (dist[i] <= rightMax):
            isContains=True
        TrueAns.append(isContains)    
    r=genRandom(dimension,999999999)
    print("r:")
    print(r)
    dist=dist+r
    dist=dist//p
    dist=dist%q
    print("((dist+r)/p)%q:")
    print(dist)
    #     print(dist[:5])




    # 生成维度为4000的ndarray，所有值都是constant_value  

    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    thresh=thresh%q
    print("((threshold+r)/p)%q:")
    print(thresh)



    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    rightM=rightM%q
    print("((rightM+r)/p)%q:")
    print(rightM)
    ans=[]
    for i in range(dimension):  # 0 到 4
        #print(i)
        left=thresh[i]
        right=rightM[i]
        sim=dist[i]
        #print(left)
        #print(right)
        #print(sim)
       #转换为字符串（默认）
        str_sim = "{}".format(sim)
        #print(str_sim) 
        simHash=sha256_string(str_sim)
        #print(simHash)
        # 组合两个条件：dist > thresh 且 dist <= rightM
        start = left+1  # 起始数字
        count = (rightMax-threshold)//p  # 往后数 right-left 个数（包括起始数字）
        Hashs=[]
        for i in range(start, start + count):
            num=i%q
            str_num= "{}".format(num)
            SetHash=sha256_string(str_num)
            Hashs.append(SetHash)
            #print(i)
        #print(Hashs)
        isContain=False
        for i in range(count):
            if simHash==Hashs[i]:
                isContain=True
        ans.append(isContain)   
    print(TrueAns)
    print(ans)

    sameCount=0
    diffCount=0
    for i in range(dimension):
        if TrueAns[i]==ans[i]:
            sameCount=sameCount+1
        else:
            diffCount=diffCount+1


    print("相同结果的数量:", sameCount) 

    print("不同结果的数量:", diffCount)  
    return ans

In [21]:
p=100
q=1024*1024
dist = np.random.randint(-10000, 10000, size=1000)
predict_issame=hashComare(dist,p,q)
print(predict_issame)

q:
1048576
dist:
[ 2958 -7412  7340 -8258 -8596 -1721  7033  -258  1166 -2862  1921 -6873
  7619  -124  -862 -4882  7659 -2535 -1544   -63 -6317 -6289  7796  8575
 -2036  4637 -5657  9063  6256 -9209 -6393  4706  6997   334 -5401 -5104
  1370  6447 -4392  2637  4355  9372  5854 -9904 -2745  6401  -951  6313
 -8246 -1623  2966 -3464 -8683  1311 -6406  4440 -8935 -6654 -2052  8336
  8257  2979 -7200 -3882 -4257 -5738  6591  8342 -9838 -3309 -4123  6278
 -4617 -3566 -2091  4903  3839  7468  4846  3388 -8768 -9917  9747  4766
 -2182 -9509 -5503  -298 -1555 -7353 -7711 -9962 -1024  1010 -5736  8230
 -3639 -4930 -5757 -2309 -4466  -558  8659  3686  9832  5533  8116 -2470
  1490 -6492  -326 -4208  9136 -8181 -7012 -1930 -2344 -2190 -1289  6430
 -7394   844   719  5653 -5822  3883  2669  3447  5164  8963 -2414  5490
  8536 -5314 -9612 -4961 -3814  -874  6648  5842  9798  1110  5882 -3736
 -4388  4436  5189  1541  7240  5145 -2304 -8070 -4345  3361  9865  9142
 -6716 -8625 -8200  -147  8818  94

In [25]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):
    dist = np.round(dist).astype(np.int32) #注意前半部分在同态下算完应该是整数  浮点数转为整数
    q=1024*1024
    p=50
    predict_issame=hashComare(dist,p,q)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
       # threshold=4000
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    #thresholds = np.arange(-10000, 10000, 100) 
    #thresholds = np.arange(-40000, 40000, 100) 
    thresholds=[2000]
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 10)
    #thresholds = np.arange(-1, 1, 0.001)
    #thresholds = np.arange(-40000, 40000,10)
    thresholds=[2000]
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
#             path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
#             path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            path0 = add_extension(os.path.join(lfw_dir, pair[1]))
            path1 = add_extension(os.path.join(lfw_dir, pair[2]))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[1]))
            path1 = add_extension(os.path.join(lfw_dir, pair[3]))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [26]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(14000, 512)
q:
1048576
dist:
[6588 5710 5179 ... -455 1153 1250]
r:
[272601812 233681073 346394645 ... 438748385 840221716  35635086]
((dist+r)/p)%q:
[209288 479431 636540 ... 386350  27241 712726]
((threshold+r)/p)%q:
[209196 479357 636476 ... 386399  27258 712741]
((rightM+r)/p)%q:
[209356 479517 636636 ... 386559  27418 712901]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

q:
1048576
dist:
[ 6588  5710  5179  5401  6785  6153  4369  4392  3645  5770  5931  4185
  5696  4730  4879  2611  4808  5998  6308  5178  5275  4378  5960  3994
  5729  5553  6218  4716  4443  4052  3841  5254  5459  4641  4969  4845
  6596  6288  6207  6949  6266  6758   975  1545  3864  3297  4058   538
  4282  3886  4979  4333  2676  3492  6134  6202  4531  6472  5371  4162
  5013  4473  4170  6282  7137  6517  6930  5959  7060  7058  5894  5641
  5408  5632  5047  5774  5277  2349  4987  4268  5355  4092  5124  3634
  6617  5264  5765  4974  5430  6810  5928  5445  5911  5416  4308  6224
  5378  4722  3288  3964  5225  3362  4551  3184  6744  3497  4040  4552
  4514  3071  3134  3574  6419  6449  4653  5929  5677  6196  5498  6544
  4215  4455  5526  4664  4625  4526  4463  3618  6889  5224  6618  6301
  6298  5724  5627  5898  4942  5044  5360  4263  5334  5147  5679  5891
  3226  4325  3751  5091  5473  6576  6683  6466  5628  5589  3249  5416
  4518  6527  2792  5705  6224  43

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, T

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[261667792 258333284  92427693  42848710 263757681 192627373 440980835
 589292655 985005384 281072065 671838116 602646634 602829685 667254377
 927981918 315143113 440990098 445933466 980179648 715688924 689246132
 654427923 386736739 344319839 389126328 404563615   4810376 476421377
 800747752 655935589 603598400 367758871 681204899 775557859  16382303
 795629004 691976814 469307751 147942097 332176110 267876007 606133941
 663552025 619000814 656294949 158797850 106000842 372617642  41375203
 359783579 198704040 665432447 297644945 520283925 957446011 187358252
 761795127 202532007 620646958 151741331 713144256  12322704 962302273
  10964509 637447008 971151913 173624422 951208973 163313166 657088730
 110136080 980363803 367308323 630584844 413134559 702026055 226602994
  52615154 724248047 981045735 134756362 220241165 971693065 350572957
 478804198 455532283 191495821 762474884 632502530 846595421 884874885
 199053747 933909892 546810042 866282677 788903898 162489401 296582568
 73602

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

  995804  622805  417576  845587  101097  193719  747242]
((threshold+r)/p)%q:
[ 685866  406404   19894  698961    4817  350463  675203  175972   20638
 1009312  139754  250899  163917  174534 1014788  143228  723675  755124
   48842  915945  259650  741972  384917  405659  813176  908737  263990
  904942   73007  422899  897385  443109  106403  680871  678290  544822
  238703  280856 1002791   40457  360622  322399  969903  615206  832304
  334697  510246  528234  748915  403969  912117  250868  286020  105657
    7851  824819   38930  674008   83852  624928   33995  519938  461595
  423286  227349 1004508  960884  342649  135810 1008406  321254   67355
  407498  188895  201029  764607 1007344 1020996  858691    3785  668391
    2590  658405  782913  444328  537196  113542  463213  375785  803214
  416489  650921  974699 1002965  434154  875288  108855  536558 1015832
 1020433   31211  830134    8310   61567  110840  878215  936668  317511
  246712  218878  854101  339631  337535  573

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[ 460614 1014772  800527  773047  503629  233009  251989  183426  403543
  798576  869268 1026032  484405  751574  259728  257716  165820  817576
  497461   45100  131960 1024191  388949  805126  356655  852211  847825
  242553  147700  371898  306736  175695  633371  823247   40291  684079
    9574  522044  308524  378794   38411  736072  552990  380743  901976
  844500  217484  946364  712608  244217  292742  354287  200086  879757
  494657  476393  826686  202936  743411  668095  177608  169324  467532
   28140  738956  687358  870644  782430  669925  477607   61174  727563
  238441  977926  289053  238055   40749   85271  446449  314773  374334
   74473  452229   54060  863674  828090 1009638  848433  999329  256563
  159923  952076  145950  853498   11481 1046935  880668   96736  553312
   65268  387428  195271 1011682  434535  436727  904405  330408  188102
  354926  456801  496040  823723  560382  684991  673261  962272  488916
  833880  956498  986494  237293  238537  822960  6

((dist+r)/p)%q:
[224046   1867 254009 ... 953898 759774 201812]
((threshold+r)/p)%q:
[224020   1820 253998 ... 953947 759791 201827]
((rightM+r)/p)%q:
[224180   1980 254158 ... 954107 759951 201987]
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True,

q:
1048576
dist:
[ 4482  6418  5435  5931  6571  6655  6176  4941  3790  4906  3652  4900
  5014  6131  5206  4724  5346  5931  5605  4880  5980  3366  5626  6623
  4330  5376  4296  4794  5272  4485  4127  5224  3430  4211  4603  6268
  6103  6014  5288  6236  4944  5648  3695  5161  5091  4787  5612  4192
  5280  4762  5405  5525  5046  5856  4921  4270  4207  3971  3064  4324
  5574  4843  4502  5289  5949  4520  5690  6660  6801  6773  6325  6281
  5892  6150  5681  5924  5853  5530  5713  6568  6231  5266  3067  5604
  5475  4283  4696  5059  4712  5446  4786  5801  5249  4726  4611  5269
  6270  5772  3787  4638  3697  4438  4686  4883  4140  3340  5099  4421
  6128  5607  4957  5718  5581  3431  3935  4429  3498  3512  4735  5515
  6068  4162  4917  4253  4708  3376  4256  4625  4710  5128  5570  4505
  4566  5089  3627  5541  4564  5431  3905  4549  5980  5689  5064  4599
  4336  5126  5169  6322  5793  7072  6399  6182  7199  6724  4001  4798
  4421  5860  5719  5845  5506  47

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, False, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

In [27]:
print(accuracy)
np.mean(accuracy)





[0.99428571 0.99       0.99714286 0.99285714 0.99428571 0.99714286
 0.99571429 0.99571429 0.99       0.99714286]


0.9944285714285714

In [38]:
np.mean(all_threshold)


2000.0

In [26]:
print(len(pairs))

7000


In [1025]:
    #a little test for look the error situation
    dist = np.array([2100,2200.2299,2500, 3000, 4000,5000,9000,10000])
    p=1000
    dimension=dist.shape[0]
    r=genRandom(dimension,99999999)
    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[55633634 45308601 12542928 70346752  9871909 11995441 77442695 64250201]
[55635. 45310. 12545. 70349.  9875. 12000. 77451. 64260.]
[55635 45310 12545 70349  9874 11997 77444 64252]
[55643 45318 12552 70356  9881 12005 77452 64260]
[False False False False  True  True  True  True]
