### Arcface LFW AgeDB CFP-FP evaluation


In [1]:
#from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training, extract_face
import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [2]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\lfw'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\LFW_pairs.txt'

In [3]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathLFW.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\lfw\\Aaron_Eckhart\\Aaron_Eckhart_0001.jpg', 'D:\\lfw\\Aaron_Guiel\\Aaron_Guiel_0001.jpg', 'D:\\lfw\\Aaron_Patterson\\Aaron_Patterson_0001.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0001.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0002.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0003.jpg', 'D:\\lfw\\Aaron_Peirsol\\Aaron_Peirsol_0004.jpg', 'D:\\lfw\\Aaron_Pena\\Aaron_Pena_0001.jpg', 'D:\\lfw\\Aaron_Sorkin\\Aaron_Sorkin_0001.jpg', 'D:\\lfw\\Aaron_Sorkin\\Aaron_Sorkin_0002.jpg', 'D:\\lfw\\Aaron_Tippin\\Aaron_Tippin_0001.jpg', 'D:\\lfw\\Abbas_Kiarostami\\Abbas_Kiarostami_0001.jpg', 'D:\\lfw\\Abba_Eban\\Abba_Eban_0001.jpg', 'D:\\lfw\\Abdel_Aziz_Al-Hakim\\Abdel_Aziz_Al-Hakim_0001.jpg', 'D:\\lfw\\Abdel_Madi_Shabneh\\Abdel_Madi_Shabneh_0001.jpg', 'D:\\lfw\\Abdel_Nasser_Assidi\\Abdel_Nasser_Assidi_0001.jpg', 'D:\\lfw\\Abdel_Nasser_Assidi\\Abdel_Nasser_Assidi_0002.jpg', 'D:\\lfw\\Abdoulaye_Wade\\Abdoulaye_Wade_0001.jpg', 'D:\\lfw\\Abdoulaye_Wade\\Abdoulaye_Wade_0002.jpg', 'D:\\lfw\\Abd

In [4]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [5]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [6]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [7]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsLFW.txt')

In [8]:
print(len(crop))
print(len(message))

13233
13233


In [9]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [10]:
mess=message

In [11]:
print(mess)

[[ 1.1628096  -0.85084873  1.2422147  ... -0.98252064 -0.69344217
  -1.0288785 ]
 [-0.23853248 -1.2733148  -0.42157245 ... -0.05360752 -0.38319495
   0.6318322 ]
 [ 0.7250262   0.02286638 -1.1436646  ...  0.6627271   1.6255715
   0.8349597 ]
 ...
 [-1.1354966   0.2686497  -0.38320267 ...  0.50229514  0.836322
   1.4965911 ]
 [-0.504686    1.0311847  -0.8311979  ... -2.7869985  -1.9792159
   1.271286  ]
 [-1.7138352   1.3578902  -0.3757491  ...  2.2136726   1.7626736
   1.675812  ]]


In [12]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[ 0.05194577 -0.03800966  0.05549301 ... -0.04389179 -0.03097789
  -0.04596271]
 [-0.01037856 -0.05540198 -0.01834263 ... -0.00233247 -0.01667283
   0.02749104]
 [ 0.03016753  0.00095144 -0.04758661 ...  0.02757534  0.06763822
   0.03474174]
 ...
 [-0.0491417   0.01162654 -0.01658414 ...  0.02173818  0.0361941
   0.06476904]
 [-0.02269937  0.04637981 -0.03738496 ... -0.12535143 -0.08901961
   0.0571789 ]
 [-0.07017887  0.05560349 -0.01538634 ...  0.09064644  0.07217873
   0.06862188]]


In [13]:
mess=np.around(message,2)


In [14]:
print(mess)

[[ 0.05 -0.04  0.06 ... -0.04 -0.03 -0.05]
 [-0.01 -0.06 -0.02 ... -0.   -0.02  0.03]
 [ 0.03  0.   -0.05 ...  0.03  0.07  0.03]
 ...
 [-0.05  0.01 -0.02 ...  0.02  0.04  0.06]
 [-0.02  0.05 -0.04 ... -0.13 -0.09  0.06]
 [-0.07  0.06 -0.02 ...  0.09  0.07  0.07]]


In [15]:
mess=mess*100

In [16]:
em_dict = dict(zip(crop,mess))

In [17]:
import random
import numpy as np
def genRandom(d,end):
    randNum=[]
    for i in range(0,d):
        b=random.randint(0,end)
        randNum.append(b)
    return np.array(randNum)    


In [18]:
s=genRandom(400,999)
print(s)

[666 335  35 181 834 483 726  97  89  65 662 243 605 715 975 342 139 114
 307 974 439 407  65 639 442 827 867 304 372 784 811 261 774 795 450 150
 217   9 975 920 852 104 638 652 886 872 627 244 220 829 902 791 182 118
 631 863 133 706 161 657 789 605 396 610 911   4 848 943  21 910 322 136
 997 774 376 695 258 918 890 325 165  34 528 481  37 921 492 977 570 579
  42 573  80 165 625  32 496 519 893 422 558 925 952 787  74 616 475 693
 571 681 385 462 111 436 235 972 148 974 282 100 851 232  81 535 824 801
 867  68   9 718 308  92 390 245 808   8 535 397 350 128 408 541 466  96
 103 735 169 194 414  12 916 543 893 975 532 220 205 456 381  74 604 404
 918 976 499 383 883 844 640 298 768 916  35 610 996 705 536 886 185 419
 973 123 454 429  79 558 963 722 260 743 951 336 992 572 288 961 170 908
 548 314 664 584 346 272 565 688 921 365 424 223  56  80 134 558 409  79
 357 777 100 818 740 508 158 892 654  58 989 883 451 409 252 512 149 394
  63 530 294 648 595 401 927 650 676  48 958 239 57

In [19]:
import hashlib
import time
# 要测量的代码
def sha256_string(input_string):
    # 将字符串编码为 UTF-8 字节
    encoded_string = input_string.encode('utf-8')
    # 创建 SHA-256 哈希对象
    sha256_hash = hashlib.sha256(encoded_string)
    # 获取十六进制格式的哈希值
    return sha256_hash.hexdigest()



 
# 示例
text = "Hello, World!"

start = time.perf_counter()
hashed_text = sha256_string(text)

 
end = time.perf_counter()
elapsed = end - start

print(f"SHA-256 哈希值: {hashed_text}")
# 计算耗时（秒）
print(f"代码执行耗时: {elapsed:.9f} 秒")


SHA-256 哈希值: dffd6021bb2bd5b0af676290809ec3a53191dd81c7f70a4b28688a362182986f
代码执行耗时: 0.000044100 秒


In [20]:
#离散的hash阈值比较方法

import numpy as np
def hashComare(dist,p,q):
    #q=1024*1024  #明文模数
    print("q:")
    print(q)
    threshold=2000
    rightMax=10000
    # 生成 10 个 [0, 10000) 的随机整数
    #dist = np.random.randint(0, 10000, size=10000)
    print("dist:")
    print(dist)
    #p=1
    dimension=dist.shape[0]
    TrueAns=[]
    for i in range(dimension):
        isContains=False
        if (dist[i] > threshold) and (dist[i] <= rightMax):
            isContains=True
        TrueAns.append(isContains)    
    r=genRandom(dimension,999999999)
    print("r:")
    print(r)
    dist=dist+r
    dist=dist//p
    dist=dist%q
    print("((dist+r)/p)%q:")
    print(dist)
    #     print(dist[:5])




    # 生成维度为4000的ndarray，所有值都是constant_value  

    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    thresh=thresh%q
    print("((threshold+r)/p)%q:")
    print(thresh)



    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    rightM=rightM%q
    print("((rightM+r)/p)%q:")
    print(rightM)
    ans=[]
    for i in range(dimension):  # 0 到 4
        #print(i)
        left=thresh[i]
        right=rightM[i]
        sim=dist[i]
        #print(left)
        #print(right)
        #print(sim)
       #转换为字符串（默认）
        str_sim = "{}".format(sim)
        #print(str_sim) 
        simHash=sha256_string(str_sim)
        #print(simHash)
        # 组合两个条件：dist > thresh 且 dist <= rightM
        start = left+1  # 起始数字
        count = (rightMax-threshold)//p  # 往后数 right-left 个数（包括起始数字）
        Hashs=[]
        for i in range(start, start + count):
            num=i%q
            str_num= "{}".format(num)
            SetHash=sha256_string(str_num)
            Hashs.append(SetHash)
            #print(i)
        #print(Hashs)
        isContain=False
        for i in range(count):
            if simHash==Hashs[i]:
                isContain=True
        ans.append(isContain)   
    print(TrueAns)
    print(ans)

    sameCount=0
    diffCount=0
    for i in range(dimension):
        if TrueAns[i]==ans[i]:
            sameCount=sameCount+1
        else:
            diffCount=diffCount+1


    print("相同结果的数量:", sameCount) 

    print("不同结果的数量:", diffCount)  
    return ans

In [21]:
p=100
q=1024*1024
dist = np.random.randint(-10000, 10000, size=1000)
predict_issame=hashComare(dist,p,q)
print(predict_issame)

q:
1048576
dist:
[-8554  8936  -742 -8076  6072 -6297  4429  5885  3631 -8037 -6419  8953
  2384   954  3773  7031  2465  6845 -2892 -8594 -2718  5154   573 -2738
  5772 -3950  4724 -1233  -532 -3445  4205 -6017  -480  7902   316  6103
 -3958 -5979 -8164 -1157 -9484  5063 -9340 -7949 -1192  9012 -6696 -1489
 -3967  1854  1280  3309  1560 -8251  5668  4401 -1122  2297   245   842
 -3023  2236  -529  6203  8649 -4154  8133 -7159 -1177  2662  -424 -8390
   231 -6325   746 -4719 -9416  -669  1050  3882 -9915  4326  1871  9515
  -542  5926  -926 -7202 -2896 -8394  4657 -7727  1423 -8999   649  -602
 -2420 -6342  6154  6790  6109  7171  1640  9920 -9390  4340 -8665  7399
  -544  1335 -8479   119  5729 -8067 -1494 -3615  6926  4641 -1610 -2403
  3347  9757 -9423 -1967  9965 -4609  7549   585 -1446 -8946  4303 -6681
 -8602 -4954  2462 -3842 -9648 -1071 -9178  4698 -1625 -4737   842 -8511
  5364  9910 -5640 -5841 -2078  9458  1127   278  -564   881  1056     3
    -7  4203  6050 -8769  2496 -57

In [34]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):

    dist = np.round(dist).astype(np.int32) #注意前半部分在同态下算完应该是整数  浮点数转为整数
    q=1024*1024
    p=500
    predict_issame=hashComare(dist,p,q)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
       # threshold=4000
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    #threshold=0.41
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    #thresholds = np.arange(-10000, 10000, 5000) 
    thresholds=[2000]
    #thresholds = np.arange(-40000, 40000, 100) 
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 5000)
    thresholds=[2000]
    #thresholds = np.arange(-1, 1, 0.001)
    #thresholds = np.arange(-40000, 40000,10)
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path+'.jpg'

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[2], pair[2] + '_' + '%04d' % int(pair[3])))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [35]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(12000, 512)
q:
1048576
dist:
[7268 7255 7672 ...  178  932 -413]
r:
[253587476 298368363 761634092 ... 744548089 912676962 300195319]
((dist+r)/p)%q:
[507189 596751 474707 ... 440520 776779 600389]
((threshold+r)/p)%q:
[507178 596740 474696 ... 440524 776781 600394]
((rightM+r)/p)%q:
[507194 596756 474712 ... 440540 776797 600410]


[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tru

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, Tr

In [36]:
print(accuracy)
np.mean(accuracy)





[0.99666667 0.99833333 1.         0.99833333 0.995      1.
 0.99666667 1.         1.         0.99833333]


0.9983333333333333

In [33]:
np.mean(all_threshold)


2310.0

In [92]:
print(len(pairs))

6000


In [1025]:
    #a little test for look the error situation
    dist = np.array([2100,2200.2299,2500, 3000, 4000,5000,9000,10000])
    p=1000
    dimension=dist.shape[0]
    r=genRandom(dimension,99999999)
    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[55633634 45308601 12542928 70346752  9871909 11995441 77442695 64250201]
[55635. 45310. 12545. 70349.  9875. 12000. 77451. 64260.]
[55635 45310 12545 70349  9874 11997 77444 64252]
[55643 45318 12552 70356  9881 12005 77452 64260]
[False False False False  True  True  True  True]
