### Arcface LFW AgeDB CFP-FP evaluation


In [1]:
#from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training, extract_face
import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [2]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\cfp-dataset\\Data\\Images'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\CFP-FP_pairs.txt'

In [3]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathCFP.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\cfp-dataset\\Data\\Images\\001\\frontal\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\04.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\05.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\06.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\07.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\08.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\09.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\frontal\\10.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\001\\profile\\04.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\01.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\02.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\03.jpg', 'D:\\cfp-dataset\\Data\\Images\\002\\frontal\\04.jpg', 'D:\\cfp-

In [4]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [5]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [6]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [7]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsCFP.txt')

In [8]:
print(len(crop))
print(len(message))

7000
7000


In [9]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [10]:
mess=message

In [11]:
print(mess)

[[-0.20975795 -0.31422865  0.9899609  ... -1.0005665   1.6652839
   0.35827792]
 [-0.85788     0.40209806  1.9207904  ... -1.2201699   1.5468774
  -0.67000705]
 [ 0.3197568  -0.3054607   2.4569337  ... -1.0209755   1.4487946
  -0.54525524]
 ...
 [-0.76567423  1.3571008   0.24274501 ... -0.454822    0.04900911
  -0.17586017]
 [ 0.12129052  0.6489141  -0.41557878 ...  0.3081193   1.6559165
  -0.10086884]
 [-1.2653039   0.6110462   1.7767196  ... -0.81409276  0.51278746
   0.3121134 ]]


In [13]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[-0.00822094 -0.01231541  0.03879906 ... -0.03921472  0.06526667
   0.01404181]
 [-0.03790472  0.01776637  0.08486855 ... -0.05391221  0.06834751
  -0.02960371]
 [ 0.01276249 -0.01219189  0.09806386 ... -0.0407503   0.05782589
  -0.02176283]
 ...
 [-0.03770983  0.06683788  0.01195531 ... -0.0224002   0.00241372
  -0.0086612 ]
 [ 0.00489605  0.02619425 -0.01677537 ...  0.01243763  0.0668432
  -0.0040717 ]
 [-0.05516742  0.0266417   0.07746522 ... -0.03549456  0.0223576
   0.01360819]]


In [57]:
#mess=np.around(message,8)
mess=message

In [58]:
print(mess)

[[-0.00822094 -0.01231541  0.03879906 ... -0.03921472  0.06526667
   0.01404181]
 [-0.03790472  0.01776637  0.08486855 ... -0.0539122   0.06834752
  -0.02960372]
 [ 0.01276249 -0.01219188  0.09806386 ... -0.0407503   0.0578259
  -0.02176283]
 ...
 [-0.03770983  0.06683788  0.01195531 ... -0.0224002   0.00241372
  -0.0086612 ]
 [ 0.00489605  0.02619425 -0.01677537 ...  0.01243763  0.0668432
  -0.0040717 ]
 [-0.05516742  0.0266417   0.07746522 ... -0.03549456  0.0223576
   0.01360819]]


In [15]:
# mess=mess*100

In [59]:
em_dict = dict(zip(crop,mess))

In [17]:
# import random
# import numpy as np
# def genRandom(d,end):
#     randNum=[]
#     for i in range(0,d):
#         b=random.randint(0,end)
#         randNum.append(b)
#     return np.array(randNum)    


In [18]:
# s=genRandom(400,999)
# print(s)

[251  21 222   1 429 411 930 293 229 301 999 620 981 194 889 925 328 803
 994 235 667 242 580 390 485 547 114 775 323 660  76 194 398 784 524 979
 680  50 862 655 567 565 866 384 958 587 819  87 668 417  99 628 147 470
 985 476 657 955  69 572 211 659 186 541 222 223 686 502 719 369 948 716
 235 337 818 954 509 537 288 534 906  31 345 261 325 850 792 434 577 463
 324 471 189 262 900 316 961 587 278  98  82 797 118 706 114 258 665 584
 235 582 783 103 217 834 826 738 197 702 215 346 819 251 961 729 115 484
 924 840 490 715 231 120  71  46 484 415 172 907 102 375 242 476 661 267
 532 248 960 566 561 797   9 894 872 580 710 154  78 184 321 642 689 297
 291 534 460 840 524 859 348 363 326 928 910 619 465 984 549 973 104 853
  47 706 156 264 184 547 962 777 682 676 288 254 525 822 641 929 791 366
 486 378 675 222 210  13 692 412 535 511 882 212 689 184 868 516 143 887
 134 190 600 167 776 836 619  47 471   7 428 678 409 376  21 119 740 898
 518  45 498 538 907 759 681  37 217 505  57 857  3

In [60]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):
    
    #print(dist)
    #dist=np.around(dist,2)
    #print(dist)
    #threshold=4000
    #predict_issame = np.less(dist, threshold)
    #print(dist)
    
#     p=8000
#     dimension=dist.shape[0]
#     r=genRandom(dimension,99999999)
#     dist=dist+r
#     dist=dist//p
    
    
    
   

#     # 生成维度为4000的ndarray，所有值都是constant_value  
#     threshold=2000
#     thresh = np.full(dimension, threshold)  
#     thresh=thresh+r
#     thresh=thresh//p

#     rightMax=10000
    
#     rightM= np.full(dimension, rightMax)  
#     rightM=rightM+r
#     rightM=rightM//p
    
# #     打印ndarray的前几个元素以验证  
# #     print(thresh[:500])
    
# #     dist = [int(num) for num in dist]
# #     #print(dist)
# #     threshold=40
    
#     print(type(dist))
    
    
   
#     #print(len(dist))
#     # 组合两个条件：dist > thresh 且 dist <= rightM
#     predict_issame = (dist > thresh) & (dist <= rightM)
    #predict_issame = np.greater(dist, thresh)
    threshold=0.2
    predict_issame = np.greater(dist, threshold)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    thresholds=[0.2]
    #thresholds = np.arange(-10000, 10000, 100) 
    #thresholds = np.arange(-40000, 40000, 100) 
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 10)
    #thresholds = np.arange(-1, 1, 0.001)
    thresholds=[0.2]
    #thresholds = np.arange(-40000, 40000,10)
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
#             path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
#             path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            path0 = add_extension(os.path.join(lfw_dir, pair[1]))
            path1 = add_extension(os.path.join(lfw_dir, pair[2]))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[1]))
            path1 = add_extension(os.path.join(lfw_dir, pair[3]))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [56]:
# import numpy as np  
  
# # 定义常数  
# constant_value = 4000  # 你可以将这里的值改为任何你需要的常数  
  
# # 生成维度为4000的ndarray，所有值都是constant_value  
# ndarray = np.full(4000, constant_value)  
  
# # 打印ndarray的前几个元素以验证  
# print(ndarray[:500])

In [40]:
#mess=np.around(message,8)
# mess=message

# 

In [74]:
# mess=np.around(message,8)

In [75]:
# em_dict = dict(zip(crop,mess))

In [61]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(14000, 512)
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0


In [62]:
print(accuracy)
np.mean(accuracy)





[0.99428571 0.98714286 0.99714286 0.99428571 0.99428571 0.99714286
 0.99571429 0.99714286 0.99       0.99714286]


0.9944285714285714

In [37]:
np.mean(all_threshold)


1894.0

In [26]:
print(len(pairs))

7000


In [1025]:
    #a little test for look the error situation
    dist = np.array([2100,2200.2299,2500, 3000, 4000,5000,9000,10000])
    p=1000
    dimension=dist.shape[0]
    r=genRandom(dimension,99999999)
    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[55633634 45308601 12542928 70346752  9871909 11995441 77442695 64250201]
[55635. 45310. 12545. 70349.  9875. 12000. 77451. 64260.]
[55635 45310 12545 70349  9874 11997 77444 64252]
[55643 45318 12552 70356  9881 12005 77452 64260]
[False False False False  True  True  True  True]
