### Arcface LFW AgeDB CFP-FP evaluation


In [2]:
#from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training, extract_face
import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [4]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\AgeDB_data\\AgeDB'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\AgeDB_pairs.txt'

In [5]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathAgeDB.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0001.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0002.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0003.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0004.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0005.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0006.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0007.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0008.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0009.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0010.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0011.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0012.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0013.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0014.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0015.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0016.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0017.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_00

In [6]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [6]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [7]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [8]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsAgeDB.txt')

In [9]:
print(len(crop))
print(len(message))

16557
16557


In [10]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [11]:
mess=message

In [12]:
print(mess)

[[-0.19722901  1.4794115   1.514209   ...  0.68148124 -0.30915388
  -0.28762692]
 [ 0.8110042   0.4261402   1.1972523  ...  0.3423461  -0.2237148
  -1.0955627 ]
 [ 0.02066806  1.8132843   1.0093315  ...  0.97316676 -1.8209513
   0.04822047]
 ...
 [ 1.6878786  -0.36986938 -0.291623   ... -0.7688866  -0.23188183
   0.22286697]
 [-1.3422089   0.38587153  0.37511122 ... -1.4931929   0.14186287
   2.1336303 ]
 [ 1.3106097  -0.5189201   0.19899347 ...  0.35538593 -0.18829477
  -0.26763454]]


In [13]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[-0.0087226   0.0654281   0.06696705 ...  0.03013903 -0.01367257
  -0.01272052]
 [ 0.04065377  0.02136142  0.06001549 ...  0.01716102 -0.01121431
  -0.05491802]
 [ 0.0008452   0.07415237  0.04127556 ...  0.03979664 -0.07446591
   0.00197193]
 ...
 [ 0.0740085  -0.01621768 -0.01278681 ... -0.03371341 -0.01016733
   0.00977206]
 [-0.05664577  0.01628509  0.01583097 ... -0.06301782  0.0059871
   0.09004645]
 [ 0.05109572 -0.02023073  0.007758   ...  0.01385515 -0.0073409
  -0.01043406]]


In [14]:
mess=np.around(message,5)


In [15]:
print(mess)

[[-0.00872  0.06543  0.06697 ...  0.03014 -0.01367 -0.01272]
 [ 0.04065  0.02136  0.06002 ...  0.01716 -0.01121 -0.05492]
 [ 0.00085  0.07415  0.04128 ...  0.0398  -0.07447  0.00197]
 ...
 [ 0.07401 -0.01622 -0.01279 ... -0.03371 -0.01017  0.00977]
 [-0.05665  0.01629  0.01583 ... -0.06302  0.00599  0.09005]
 [ 0.0511  -0.02023  0.00776 ...  0.01386 -0.00734 -0.01043]]


In [16]:
mess=mess*100000

In [17]:
em_dict = dict(zip(crop,mess))

In [18]:
import random
import numpy as np
def genRandom(d,end):
    randNum=[]
    for i in range(0,d):
        b=random.randint(0,end)
        randNum.append(b)
    return np.array(randNum)    


In [19]:
s=genRandom(400,999)
print(s)

[464 598  43 563 170 238 392 523  20 352 696 356 109 768 356 307 248 210
 823  67 710  27 271  41 158 206 843 813 565 610 177 361 607 796 284 402
 312  36 373 378 666 828 635 580 949 641 861 356 546  28 676 204 525 779
 335 779 432  97 821 192 549 362 197 195 174  97 181 576 413 666 109 402
 409 490 339 600 545 652 498 682 171 131 922 103 439 734 620 755 519 371
 300 839 642 621 569 807 352 226 944 214 766 243 344 842 166 199 353 843
 955 365 687 246 611 113 427 421 361 671  45 511  84 384 931 582 930  79
 590  63 607 251 325 446 499 406 140 517 768 142 460 496 513  55 659  51
 854 526 377 589 678 982 625 627 112 583 778  50 281 343  67 107 243 821
 690 854 759 834 483 294 369 597 898  12 961 906 837 456 674  64 282 226
 935 149 757 201 937 159 731 461 882 449 319  93  30 140  65 833 195  53
 884 365 615 477 362 214 633  20  67 218  83 580  28 902 459 225 480 646
 311  75 134 519 297 228 518 688 562 869 222 136 132 545 388 672 462 773
 948 911  40 431 311 897  42 620  43 736 872  61 84

In [20]:
import hashlib
import time
# 要测量的代码
def sha256_string(input_string):
    # 将字符串编码为 UTF-8 字节
    encoded_string = input_string.encode('utf-8')
    # 创建 SHA-256 哈希对象
    sha256_hash = hashlib.sha256(encoded_string)
    # 获取十六进制格式的哈希值
    return sha256_hash.digest()



 
# 示例
text = "Hello, World!"

start = time.perf_counter()
hashed_text = sha256_string(text)

 
end = time.perf_counter()
elapsed = end - start

print(f"SHA-256 哈希值: {hashed_text}")
# 计算耗时（秒）
print(f"代码执行耗时: {elapsed:.9f} 秒")


SHA-256 哈希值: b'\xdf\xfd`!\xbb+\xd5\xb0\xafgb\x90\x80\x9e\xc3\xa51\x91\xdd\x81\xc7\xf7\nK(h\x8a6!\x82\x98o'
代码执行耗时: 0.000040100 秒


In [21]:
#离散的hash阈值比较方法

import numpy as np
def hashComare(dist,p,q,y):
    
    #q=1024*1024  #明文模数
    print("q:")
    print(q)
    threshold=2000
    rightMax=10000
    #y表示向量保留多少位小数，保留的小数越多最后化成整数的区间越大
    factor=pow(10,y-2)
    threshold=threshold*factor*factor
    rightMax=rightMax*factor*factor
    p=p*factor*factor
    threshold=int(threshold)
    rightMax=int(rightMax)
    p=int(p)
    
    
    
    # 生成 10 个 [0, 10000) 的随机整数
    #dist = np.random.randint(0, 10000, size=10000)
    print("dist:")
    print(dist)
    #p=1
    dimension=dist.shape[0]
    TrueAns=[]
    for i in range(dimension):
        isContains=False
        if (dist[i] > threshold) and (dist[i] <= rightMax):
            isContains=True
        TrueAns.append(isContains)    
    r=genRandom(dimension,int(pow(10,20)-1)) #[0,10^17-1]
    print("r:")
    print(r)
    dist=dist+r
    dist=dist%q
    dist=dist//p
    dist=dist%q
    print("(((dist+r)%q)/p)%q:")
    print(dist)
    #     print(dist[:5])




    # 生成维度为4000的ndarray，所有值都是constant_value  

    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh%q
    thresh=thresh//p
    thresh=thresh%q
    print("(((threshold+r)%q)/p)%q:")
    print(thresh)



    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM%q
    rightM=rightM//p
    rightM=rightM%q
    print("(((rightM+r)%q)/p)%q:")
    print(rightM)
    ans=[]
    for i in range(dimension):  # 0 到 4
        print(i)
        left=thresh[i]
        right=rightM[i]
        sim=dist[i]
        #print(left)
        #print(right)
        #print(sim)
       #转换为字符串（默认）
        str_sim = "{}".format(sim)
        #print(str_sim) 
        simHash=sha256_string(str_sim)
        #print(simHash)
        # 组合两个条件：dist > thresh 且 dist <= rightM
        start = left+1  # 起始数字
        count = (rightMax-threshold)//p  # 往后数 right-left 个数（包括起始数字）
        Hashs=[]
        for i in range(start, start + count):
            num=i%q
            str_num= "{}".format(num)
            SetHash=sha256_string(str_num)
            Hashs.append(SetHash)
            #print(i)
        #print(Hashs)
        isContain=False
        for i in range(count):
            if simHash==Hashs[i]:
                isContain=True
        ans.append(isContain)   
    #print(TrueAns)
    #print(ans)

    sameCount=0
    diffCount=0
    for i in range(dimension):
        if TrueAns[i]==ans[i]:
            sameCount=sameCount+1
        else:
            diffCount=diffCount+1


    #print("相同结果的数量:", sameCount) 

    #print("不同结果的数量:", diffCount)  
    return ans

In [22]:
p=100
q=1024*1024
dist = np.random.randint(-10000, 10000, size=1000)
y=2
predict_issame=hashComare(dist,p,q,y)
print(predict_issame)

q:
1048576
dist:
[-1211  3658 -3447   780  1421  2399 -2975  1735 -7814  5674  7467  4036
 -4263 -1700 -8769  2992 -4999 -3212  9409 -3318  2163  3027  6747  9947
 -7551  8105 -6653 -4647 -6586   587 -3659 -8375 -3435  2318 -8799 -5050
 -8419  2153  1395  4369 -5281 -8049  8883  5381  7320 -8266 -8136 -4223
  5922 -3283 -6659 -2806  -415  2972 -8417  5619  3538  5158 -8392 -5083
  -571 -9543  6929   602 -4990  7769  9503 -5154  -597 -6417  9008 -4227
 -8858 -1949 -3681  6621 -8910 -3418  7110  1527  3018  2001 -1489  6105
  1756 -9069 -2641 -4926  2311 -5785  -639 -2561 -6722 -3476  6038  5860
  1029 -5701  1123 -5707 -7848   402  2694  2287 -5311 -2312  6943  8135
  7943  9982 -8470  2226  7164 -5882  6514 -8662  1272 -7645  2514  7456
 -7699 -7019   410 -3336 -3322 -1621  5743  9464  4004  3650  1641   -66
  5127  6581   -79 -2316 -2152  9101 -7857  -702  5318  5608 -6617 -6622
  2719 -4321  1895 -5084 -6472  5863   141  6004  3438 -4781  -828 -3015
  4887  1901 -1501  3053  7345  50

359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608


In [44]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  
y=5
p=2000
q=pow(2,58)

thresh=2000

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):

    dist = np.round(dist).astype(np.int64) #注意前半部分在同态下算完应该是整数  浮点数转为整数
    
    
    
    #q=q*16
    predict_issame=hashComare(dist,p,q,y)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
       # threshold=4000
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    #threshold=0.41
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    #thresholds = np.arange(-10000, 10000, 5000) 
    factor=pow(10,y-2)
    thresholds=[int(thresh*factor*factor)]
    #thresholds = np.arange(-40000, 40000, 100) 
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 5000)
    thresholds=[int(thresh*factor*factor)]
    #thresholds = np.arange(-1, 1, 0.001)
    #thresholds = np.arange(-40000, 40000,10)
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path+'.jpg'

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[2], pair[2] + '_' + '%04d' % int(pair[3])))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [45]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(12000, 512)
q:
288230376151711744
dist:
[ 904191026 5559929128 8773396611 ...    7626015  509316787  502988483]
r:
[54782258361591739304 16163855990689582610 77312712305025184956 ...
 81496323321016387028 77139102714022125440 46798590758650028799]
(((dist+r)%q)/p)%q:
[9243446 11477465 33485752 ... 107678623 90796141 52634911]
(((threshold+r)%q)/p)%q:
[9243447 11477464 33485749 ... 107678624 90796141 52634912]
(((rightM+r)%q)/p)%q:
[9243451 11477468 33485753 ... 107678628 90796145 52634916]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
15

2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963


4449
4450
4451
4452
4453
4454
4455
4456
4457
4458
4459
4460
4461
4462
4463
4464
4465
4466
4467
4468
4469
4470
4471
4472
4473
4474
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4485
4486
4487
4488
4489
4490
4491
4492
4493
4494
4495
4496
4497
4498
4499
4500
4501
4502
4503
4504
4505
4506
4507
4508
4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
4520
4521
4522
4523
4524
4525
4526
4527
4528
4529
4530
4531
4532
4533
4534
4535
4536
4537
4538
4539
4540
4541
4542
4543
4544
4545
4546
4547
4548
4549
4550
4551
4552
4553
4554
4555
4556
4557
4558
4559
4560
4561
4562
4563
4564
4565
4566
4567
4568
4569
4570
4571
4572
4573
4574
4575
4576
4577
4578
4579
4580
4581
4582
4583
4584
4585
4586
4587
4588
4589
4590
4591
4592
4593
4594
4595
4596
4597
4598
4599
4600
4601
4602
4603
4604
4605
4606
4607
4608
4609
4610
4611
4612
4613
4614
4615
4616
4617
4618
4619
4620
4621
4622
4623
4624
4625
4626
4627
4628
4629
4630
4631
4632
4633
4634
4635
4636
4637
4638
4639
4640
4641
4642
4643
4644
4645
4646
4647
4648


431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[ 5352450163  6506377175  4887090784  5076917924  6686205701  6011231914
  5214652113  6071498658  5012775790  5699531843  4921028639  4226638698
  1616829917  6763090201  6719970367  6383499489  3616237514  2448819122
  4569468546  6688524781  4490186338  6483386963  4174312322  7516627952
  59

591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[5352450163 6506377175 4887090784 ...    7626015  509316787  502988483]
r:
[31947081440565594860 3495630235137284734 17654229742519714625 ...
 86533339860158175249 30208962844755328702 29837507448101344150]
(((dist+r)%q)/p)%q:
[120870034 18432863 36088401 ... 32113507 116501862 74889352]
(((threshold+r)%q)/p)%q:
[120870032 18432861 36088399 ... 32113508 116501863 74889353]
(((rightM+r)%q)/p)%q:
[120870036 18432865 36088403 ... 32113512 116501867 74889357]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
14

2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467


4305
4306
4307
4308
4309
4310
4311
4312
4313
4314
4315
4316
4317
4318
4319
4320
4321
4322
4323
4324
4325
4326
4327
4328
4329
4330
4331
4332
4333
4334
4335
4336
4337
4338
4339
4340
4341
4342
4343
4344
4345
4346
4347
4348
4349
4350
4351
4352
4353
4354
4355
4356
4357
4358
4359
4360
4361
4362
4363
4364
4365
4366
4367
4368
4369
4370
4371
4372
4373
4374
4375
4376
4377
4378
4379
4380
4381
4382
4383
4384
4385
4386
4387
4388
4389
4390
4391
4392
4393
4394
4395
4396
4397
4398
4399
4400
4401
4402
4403
4404
4405
4406
4407
4408
4409
4410
4411
4412
4413
4414
4415
4416
4417
4418
4419
4420
4421
4422
4423
4424
4425
4426
4427
4428
4429
4430
4431
4432
4433
4434
4435
4436
4437
4438
4439
4440
4441
4442
4443
4444
4445
4446
4447
4448
4449
4450
4451
4452
4453
4454
4455
4456
4457
4458
4459
4460
4461
4462
4463
4464
4465
4466
4467
4468
4469
4470
4471
4472
4473
4474
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4485
4486
4487
4488
4489
4490
4491
4492
4493
4494
4495
4496
4497
4498
4499
4500
4501
4502
4503
4504


595
596
597
598
599
q:
288230376151711744
dist:
[  904191026  5559929128  8773396611  6192694275  6761066184  5230123541
  5896594472  6355470913  4856193202  6734698384  4194196382  5250556790
  5671170829  4145035228  6327167938  4668064493  4453776892  5734264805
  3651288162  5544034051  4507799660  6009297012   873709929  4022438240
  6040098815  5755490774  6070780395  5533703136  4862090503  5836814350
  3539808803  6762729998  3072096829  5829337371  1425799075  5480901539
  3425502570   -22290685  4164578579  5899635423  6455773513  5525360410
  2509321722  5143984205  6214614259  5028038607  4798176215  3151887917
  5514925125  3612457571  4460019390  5655932589  4094850817  3661713244
  5695120075  4239657853  4300444879  8177903873  5123884916  4741415862
  5897135486  6307273021  4088927920  4534117931  5333435951  5243833349
  3496813086  7578923205  3975162260  6113231076  7646805588  6878799460
  6770645791  6389399507  3900483004  -356351450  5625795195  6400109405
  8

q:
288230376151711744
dist:
[5352450163 6506377175 4887090784 ...    7626015  509316787  502988483]
r:
[11430291256484263021 42386861652798478587 25628300054597081917 ...
 47711613741074136413 35901107130030902289 28437150934544025272]
(((dist+r)%q)/p)%q:
[94653295 8498182 132013479 ... 76800838 80270243 95287036]
(((threshold+r)%q)/p)%q:
[94653294 8498180 132013477 ... 76800839 80270244 95287036]
(((rightM+r)%q)/p)%q:
[94653298 8498184 132013481 ... 76800843 80270248 95287040]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156

2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964
2965
2966
2967
2968
2969
2970
2971
2972
2973
2974
2975
2976
2977
2978
2979
2980
2981
2982
2983
2984
2985
2986
2987
2988
2989
2990
2991
2992
2993
2994
2995
2996
2997
2998
2999
3000
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051


4497
4498
4499
4500
4501
4502
4503
4504
4505
4506
4507
4508
4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
4520
4521
4522
4523
4524
4525
4526
4527
4528
4529
4530
4531
4532
4533
4534
4535
4536
4537
4538
4539
4540
4541
4542
4543
4544
4545
4546
4547
4548
4549
4550
4551
4552
4553
4554
4555
4556
4557
4558
4559
4560
4561
4562
4563
4564
4565
4566
4567
4568
4569
4570
4571
4572
4573
4574
4575
4576
4577
4578
4579
4580
4581
4582
4583
4584
4585
4586
4587
4588
4589
4590
4591
4592
4593
4594
4595
4596
4597
4598
4599
4600
4601
4602
4603
4604
4605
4606
4607
4608
4609
4610
4611
4612
4613
4614
4615
4616
4617
4618
4619
4620
4621
4622
4623
4624
4625
4626
4627
4628
4629
4630
4631
4632
4633
4634
4635
4636
4637
4638
4639
4640
4641
4642
4643
4644
4645
4646
4647
4648
4649
4650
4651
4652
4653
4654
4655
4656
4657
4658
4659
4660
4661
4662
4663
4664
4665
4666
4667
4668
4669
4670
4671
4672
4673
4674
4675
4676
4677
4678
4679
4680
4681
4682
4683
4684
4685
4686
4687
4688
4689
4690
4691
4692
4693
4694
4695
4696


391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[ 2396244590  5761869699  6523943052  4761730009  2616556007  5769061539
  6228231579  6905685189  5253270448   781874066  6327941124  5

q:
288230376151711744
dist:
[5352450163 6506377175 4887090784 ...    7626015  509316787  502988483]
r:
[56065787080567820988 19816421170240370859 74007555693930545141 ...
 13690610066669606520 76830675983937286066 43395222324125376466]
(((dist+r)%q)/p)%q:
[74547056 108377799 110289701 ... 71891193 80697964 80332950]
(((threshold+r)%q)/p)%q:
[74547054 108377796 110289700 ... 71891194 80697964 80332951]
(((rightM+r)%q)/p)%q:
[74547058 108377800 110289704 ... 71891198 80697968 80332955]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
1

2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355


4239
4240
4241
4242
4243
4244
4245
4246
4247
4248
4249
4250
4251
4252
4253
4254
4255
4256
4257
4258
4259
4260
4261
4262
4263
4264
4265
4266
4267
4268
4269
4270
4271
4272
4273
4274
4275
4276
4277
4278
4279
4280
4281
4282
4283
4284
4285
4286
4287
4288
4289
4290
4291
4292
4293
4294
4295
4296
4297
4298
4299
4300
4301
4302
4303
4304
4305
4306
4307
4308
4309
4310
4311
4312
4313
4314
4315
4316
4317
4318
4319
4320
4321
4322
4323
4324
4325
4326
4327
4328
4329
4330
4331
4332
4333
4334
4335
4336
4337
4338
4339
4340
4341
4342
4343
4344
4345
4346
4347
4348
4349
4350
4351
4352
4353
4354
4355
4356
4357
4358
4359
4360
4361
4362
4363
4364
4365
4366
4367
4368
4369
4370
4371
4372
4373
4374
4375
4376
4377
4378
4379
4380
4381
4382
4383
4384
4385
4386
4387
4388
4389
4390
4391
4392
4393
4394
4395
4396
4397
4398
4399
4400
4401
4402
4403
4404
4405
4406
4407
4408
4409
4410
4411
4412
4413
4414
4415
4416
4417
4418
4419
4420
4421
4422
4423
4424
4425
4426
4427
4428
4429
4430
4431
4432
4433
4434
4435
4436
4437
4438


498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[ 4705832074  6874424605  4881425472  7061957515  5576425002  5423150212
  5538964899  4715203213  6146908431  4753664253  4166076417  5119238807
  3300910051  4213195990  7319546885  6907785532  1228679882  6677252722
  5489468102  5057295453  5694098612  4961018366  4589144925  6169742798
  6450206199  7325085012  5082469249  5570756874  2633283458  5633423478
  4025451599  6248783556  6848178344  1546551849  5977338328   854137880
  3634804708  4470403469  6261444339  6449352940  4090758008  4975570748
  3954305156  6161353550  3715963803  3285506093  401

567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[5352450163 6506377175 4887090784 ...    7626015  509316787  502988483]
r:
[28507961726186076297 51761212588980694444 24826030795580626910 ...
 34269142476326658671 20704814307854173773 38441830501487521872]
(((dist+r)%q)/p)%q:
[130692434 83987632 19109225 ... 128979045 120228800 53595236]
(((threshold+r)%q)/p)%q:
[130692432 83987629 19109224 ... 128979046 120228801 53595237]
(((rightM+r)%q)/p)%q:
[130692436 83987633 19109228 ... 128979050 120228805 53595241]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
12

1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143


3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966
3967
3968
3969
3970
3971
3972
3973
3974
3975
3976
3977
3978
3979
3980
3981
3982
3983
3984
3985
3986
3987
3988
3989
3990
3991
3992
3993
3994
3995
3996
3997
3998
3999
4000
4001
4002
4003
4004
4005
4006
4007
4008
4009
4010
4011
4012
4013
4014
4015
4016
4017
4018
4019
4020
4021
4022
4023
4024
4025
4026
4027
4028
4029
4030
4031
4032
4033
4034
4035
4036
4037
4038
4039
4040
4041
4042
4043
4044
4045
4046
4047
4048
4049
4050
4051
4052
4053
4054
4055
4056
4057
4058
4059
4060
4061
4062
4063
4064
4065
4066
4067
4068
4069
4070
4071
4072
4073
4074
4075
4076
4077
4078
4079
4080
4081
4082
4083
4084
4085
4086
4087
4088
4089
4090


104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353


q:
288230376151711744
dist:
[5352450163 6506377175 4887090784 ...    7626015  509316787  502988483]
r:
[97887864381304737614 84840853430780828099 96907096345434060854 ...
 91831902719656415186 99321881246950580810 93832464145865455486]
(((dist+r)%q)/p)%q:
[88883435 50561424 30844981 ... 87321551 85315925 78795948]
(((threshold+r)%q)/p)%q:
[88883433 50561422 30844980 ... 87321552 85315926 78795949]
(((rightM+r)%q)/p)%q:
[88883437 50561426 30844984 ... 87321556 85315930 78795953]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156

2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695


4325
4326
4327
4328
4329
4330
4331
4332
4333
4334
4335
4336
4337
4338
4339
4340
4341
4342
4343
4344
4345
4346
4347
4348
4349
4350
4351
4352
4353
4354
4355
4356
4357
4358
4359
4360
4361
4362
4363
4364
4365
4366
4367
4368
4369
4370
4371
4372
4373
4374
4375
4376
4377
4378
4379
4380
4381
4382
4383
4384
4385
4386
4387
4388
4389
4390
4391
4392
4393
4394
4395
4396
4397
4398
4399
4400
4401
4402
4403
4404
4405
4406
4407
4408
4409
4410
4411
4412
4413
4414
4415
4416
4417
4418
4419
4420
4421
4422
4423
4424
4425
4426
4427
4428
4429
4430
4431
4432
4433
4434
4435
4436
4437
4438
4439
4440
4441
4442
4443
4444
4445
4446
4447
4448
4449
4450
4451
4452
4453
4454
4455
4456
4457
4458
4459
4460
4461
4462
4463
4464
4465
4466
4467
4468
4469
4470
4471
4472
4473
4474
4475
4476
4477
4478
4479
4480
4481
4482
4483
4484
4485
4486
4487
4488
4489
4490
4491
4492
4493
4494
4495
4496
4497
4498
4499
4500
4501
4502
4503
4504
4505
4506
4507
4508
4509
4510
4511
4512
4513
4514
4515
4516
4517
4518
4519
4520
4521
4522
4523
4524


170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419


218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467


1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807


3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778
3779
3780
3781
3782
3783
3784
3785
3786
3787
3788
3789
3790
3791
3792
3793
3794
3795
3796
3797
3798
3799
3800
3801
3802
3803
3804
3805
3806
3807
3808
3809
3810
3811
3812
3813
3814
3815
3816
3817
3818
3819
3820
3821
3822
3823
3824
3825
3826
3827
3828
3829
3830
3831
3832
3833
3834
3835
3836
3837
3838
3839
3840
3841
3842
3843
3844
3845
3846
3847
3848
3849
3850
3851
3852
3853
3854
3855
3856
3857
3858
3859
3860
3861
3862
3863
3864
3865
3866
3867
3868
3869
3870
3871
3872
3873
3874
3875
3876
3877
3878
3879
3880
3881
3882
3883
3884
3885
3886
3887
3888
3889
3890
3891
3892
3893
3894
3895
3896
3897
3898
3899
3900
3901
3902
3903
3904
3905
3906
3907
3908
3909
3910
3911
3912
3913
3914
3915
3916
3917
3918
3919
3920
3921
3922
3923
3924
3925
3926
3927
3928
3929
3930
3931
3932
3933
3934
3935
3936
3937
3938
3939
3940
3941
3942
3943
3944
3945
3946
3947
3948
3949
3950
3951
3952
3953
3954
3955
3956
3957
3958
3959
3960
3961
3962
3963
3964
3965
3966


482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[ 5716137473  7803605761  5561206960  5882557340  6450465998  5138199894
  4779802403  5402729745  2966222884  6560573879  4223854299  3377411880
  6064900461  4919591006  4946380500  6889010294  4318718088  3983853698
  5625281279  6368778789  5551102466  5429774516  8068212748  5362476168
  4114620263  4708856520  4929471743  5463454479  5624692125  3954617049
  4676520797  4510310126  2206496554  3015399495  3132471030  3486242881
  2234997039  6141954716  7127893865  4712580424  4206158104  

(((threshold+r)%q)/p)%q:
[128662870 102383391 137390035 ... 37127164 30079346 103430121]
(((rightM+r)%q)/p)%q:
[128662874 102383395 137390039 ... 37127168 30079350 103430125]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233

2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621


4792
4793
4794
4795
4796
4797
4798
4799
4800
4801
4802
4803
4804
4805
4806
4807
4808
4809
4810
4811
4812
4813
4814
4815
4816
4817
4818
4819
4820
4821
4822
4823
4824
4825
4826
4827
4828
4829
4830
4831
4832
4833
4834
4835
4836
4837
4838
4839
4840
4841
4842
4843
4844
4845
4846
4847
4848
4849
4850
4851
4852
4853
4854
4855
4856
4857
4858
4859
4860
4861
4862
4863
4864
4865
4866
4867
4868
4869
4870
4871
4872
4873
4874
4875
4876
4877
4878
4879
4880
4881
4882
4883
4884
4885
4886
4887
4888
4889
4890
4891
4892
4893
4894
4895
4896
4897
4898
4899
4900
4901
4902
4903
4904
4905
4906
4907
4908
4909
4910
4911
4912
4913
4914
4915
4916
4917
4918
4919
4920
4921
4922
4923
4924
4925
4926
4927
4928
4929
4930
4931
4932
4933
4934
4935
4936
4937
4938
4939
4940
4941
4942
4943
4944
4945
4946
4947
4948
4949
4950
4951
4952
4953
4954
4955
4956
4957
4958
4959
4960
4961
4962
4963
4964
4965
4966
4967
4968
4969
4970
4971
4972
4973
4974
4975
4976
4977
4978
4979
4980
4981
4982
4983
4984
4985
4986
4987
4988
4989
4990
4991


108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357


123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372


1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592


3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730
3731
3732
3733
3734
3735
3736
3737
3738
3739
3740
3741
3742
3743
3744
3745
3746
3747
3748
3749
3750
3751
3752
3753
3754
3755
3756
3757
3758
3759
3760
3761
3762
3763
3764
3765
3766
3767
3768
3769
3770
3771
3772
3773
3774
3775
3776
3777
3778


408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[ 6183739847  6694116448  5860235854  4590093432  4512955687  6687340721
  4518228523  2851921188  3884488757  5389144499  5492102815  7951533541
  4878437865  5293962260  5862512040  4589179547  48052974

472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
q:
288230376151711744
dist:
[5352450163 6506377175 4887090784 ...  249896537 1325679216  472423011]
r:
[23597290613073797657 20880691947493526380 45587096714426892697 ...
 90672867101436829104 26486235506419688432 22363627894832459064]
(((dist+r)%q)/p)%q:
[125315075 64052435 23348643 ... 84264495 128635638 84944465]
(((threshold+r)%q)/p)%q:
[125315073 64052433 23348642 ... 84264495 128635639 84944466]
(((rightM+r)%q)/p)%q:
[125315077 64052437 23348646 ... 84264499 128635643 84944470]

1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997


4104
4105
4106
4107
4108
4109
4110
4111
4112
4113
4114
4115
4116
4117
4118
4119
4120
4121
4122
4123
4124
4125
4126
4127
4128
4129
4130
4131
4132
4133
4134
4135
4136
4137
4138
4139
4140
4141
4142
4143
4144
4145
4146
4147
4148
4149
4150
4151
4152
4153
4154
4155
4156
4157
4158
4159
4160
4161
4162
4163
4164
4165
4166
4167
4168
4169
4170
4171
4172
4173
4174
4175
4176
4177
4178
4179
4180
4181
4182
4183
4184
4185
4186
4187
4188
4189
4190
4191
4192
4193
4194
4195
4196
4197
4198
4199
4200
4201
4202
4203
4204
4205
4206
4207
4208
4209
4210
4211
4212
4213
4214
4215
4216
4217
4218
4219
4220
4221
4222
4223
4224
4225
4226
4227
4228
4229
4230
4231
4232
4233
4234
4235
4236
4237
4238
4239
4240
4241
4242
4243
4244
4245
4246
4247
4248
4249
4250
4251
4252
4253
4254
4255
4256
4257
4258
4259
4260
4261
4262
4263
4264
4265
4266
4267
4268
4269
4270
4271
4272
4273
4274
4275
4276
4277
4278
4279
4280
4281
4282
4283
4284
4285
4286
4287
4288
4289
4290
4291
4292
4293
4294
4295
4296
4297
4298
4299
4300
4301
4302
4303


r:
[39654056099571282424 95328793370152192273 18054818983897616989
 1654727813125305075 11125020998490187999 82363926228587201173
 9939892492860374046 25046177096110896307 63244339094794333454
 12851827341899576604 16829247044906567371 79232547823783231761
 34616005537402092579 98235652217043040762 29513307121018352245
 76261331226426032825 65548815922292119717 40054166469577758506
 74009896005263104329 89306217137966810544 5105808255252070449
 9945076304874314700 63021438581584492910 90031944363196961412
 89492210689976742088 9371346993215014388 34151074935880376584
 37694346765720715378 98844601506112057921 40909479060359454421
 66603568145071779963 43750837447893917932 42328439834179470481
 67021360099789743814 20588636881121597416 6961916573000933157
 35766282639465206264 6694924994070500215 10311394974413080361
 12192029152740998442 61387771227296045963 49336403012623539104
 60611020694692976159 46148888445286920290 73576498399227544595
 32642372157713949302 58746282534092787108 7

In [46]:
print(accuracy)
np.mean(accuracy)







[0.96       0.94166667 0.95333333 0.96166667 0.94166667 0.95833333
 0.94166667 0.95333333 0.94       0.95166667]


0.9503333333333333

In [237]:
np.mean(all_threshold)


D:\MiniConda\envs\jucing\lib\site-packages\numpy\core\fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
D:\MiniConda\envs\jucing\lib\site-packages\numpy\core\_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [92]:
print(len(pairs))

6000


In [1025]:
    #a little test for look the error situation
    dist = np.array([2100,2200.2299,2500, 3000, 4000,5000,9000,10000])
    p=1000
    dimension=dist.shape[0]
    r=genRandom(dimension,99999999)
    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[55633634 45308601 12542928 70346752  9871909 11995441 77442695 64250201]
[55635. 45310. 12545. 70349.  9875. 12000. 77451. 64260.]
[55635 45310 12545 70349  9874 11997 77444 64252]
[55643 45318 12552 70356  9881 12005 77452 64260]
[False False False False  True  True  True  True]
