### Arcface LFW AgeDB CFP-FP evaluation


In [1]:
#from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training, extract_face
import torch
# from torch.utils.data import DataLoader, SubsetRandomSampler, SequentialSampler
# from torchvision import datasets, transforms
import numpy as np
import os

In [2]:
# data_dir = 'D:/lfw'
# pairs_path = 'pairs.txt'
data_dir = 'D:\\AgeDB_data\\AgeDB'
pairs_path = 'D:\\hash方法代码\\faceVerificationData\\data\\AgeDB_pairs.txt'

In [3]:
# 打开文件  
with open('D:\\hash方法代码\\faceVerificationData\\data\\image_pathAgeDB.txt', 'r') as file:  
    # 读取所有行并存储到列表中  
    lines = file.readlines()  
  
# 去除每行末尾的换行符（如果有的话）  
crop = [line.strip() for line in lines]  
  
# 打印结果  
print(crop)

['D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0001.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0002.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0003.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0004.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0005.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0006.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0007.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0008.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0009.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0010.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0011.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0012.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0013.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0014.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0015.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0016.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_0017.jpg', 'D:\\AgeDB_data\\AgeDB\\AbeVigoda\\AbeVigoda_00

In [4]:
def list_txt(path, list=None):
    '''

    :param path: 储存list的位置
    :param list: list数据
    :return: None/relist 当仅有path参数输入时为读取模式将txt读取为list
             当path参数和list都有输入时为保存模式将list保存为txt
    '''
    if list != None:
        file = open(path, 'w')
        file.write(str(list))
        file.close()
        return None
    else:
        file = open(path, 'r')
        rdlist = eval(file.read())
        file.close()
        return rdlist


In [5]:
# crop=list_txt(path='D:\\faceVerificationData\\data\\crop_paths.txt')




In [6]:
def loadtxtmethod(filename):
    data = np.loadtxt(filename,dtype=np.float32,delimiter=' ')
    return data

In [7]:
#message=loadtxtmethod('embeddings.txt')
message=loadtxtmethod('D:\\hash方法代码\\faceVerificationData\\data\\embeddingsAgeDB.txt')

In [8]:
print(len(crop))
print(len(message))

16557
16557


In [9]:
print(type(message[0]))

<class 'numpy.ndarray'>


In [10]:
mess=message

In [11]:
print(mess)

[[-0.19722901  1.4794115   1.514209   ...  0.68148124 -0.30915388
  -0.28762692]
 [ 0.8110042   0.4261402   1.1972523  ...  0.3423461  -0.2237148
  -1.0955627 ]
 [ 0.02066806  1.8132843   1.0093315  ...  0.97316676 -1.8209513
   0.04822047]
 ...
 [ 1.6878786  -0.36986938 -0.291623   ... -0.7688866  -0.23188183
   0.22286697]
 [-1.3422089   0.38587153  0.37511122 ... -1.4931929   0.14186287
   2.1336303 ]
 [ 1.3106097  -0.5189201   0.19899347 ...  0.35538593 -0.18829477
  -0.26763454]]


In [12]:
# 计算每一行的模长  
row_lengths = np.linalg.norm(mess, axis=1)  
  
# 标准化每一行  
message = np.divide(message, row_lengths[:, np.newaxis])  
  
print(message)

[[-0.0087226   0.0654281   0.06696705 ...  0.03013903 -0.01367257
  -0.01272052]
 [ 0.04065377  0.02136142  0.06001549 ...  0.01716102 -0.01121431
  -0.05491802]
 [ 0.0008452   0.07415237  0.04127556 ...  0.03979664 -0.07446591
   0.00197193]
 ...
 [ 0.0740085  -0.01621768 -0.01278681 ... -0.03371341 -0.01016733
   0.00977206]
 [-0.05664577  0.01628509  0.01583097 ... -0.06301782  0.0059871
   0.09004645]
 [ 0.05109572 -0.02023073  0.007758   ...  0.01385515 -0.0073409
  -0.01043406]]


In [13]:
mess=np.around(message,2)


In [14]:
print(mess)

[[-0.01  0.07  0.07 ...  0.03 -0.01 -0.01]
 [ 0.04  0.02  0.06 ...  0.02 -0.01 -0.05]
 [ 0.    0.07  0.04 ...  0.04 -0.07  0.  ]
 ...
 [ 0.07 -0.02 -0.01 ... -0.03 -0.01  0.01]
 [-0.06  0.02  0.02 ... -0.06  0.01  0.09]
 [ 0.05 -0.02  0.01 ...  0.01 -0.01 -0.01]]


In [15]:
mess=mess*100

In [16]:
em_dict = dict(zip(crop,mess))

In [17]:
import random
import numpy as np
def genRandom(d,end):
    randNum=[]
    for i in range(0,d):
        b=random.randint(0,end)
        randNum.append(b)
    return np.array(randNum)    


In [18]:
s=genRandom(400,999)
print(s)

[747 396 471 810 128 101 783 299 135 554 399 211 423 538 200 280 929 895
 123 793 391 623 650 380 133 186 585 298 794  52  53 815 864 563 159 622
 537 870 582 497 592 486  51 438 898 724  63 990 262 856 170 682 209 193
 293 747 811 616 369 495 639 777 144 526 447 463 180 593 925 329 699 966
  71 977  82 806 275 510 344 362  90 471 702 863 587 303 111 876 695 776
 574 921 637 703 304 813 886 888 740 226 614 541 505 738 382 151 270 140
 968 488  23  18 316 344 587  99 181 488   9 832  39 734 256 970 797 675
  89 955 939 374 682 326 220 592 196 413 570 705 541 725 263 463 750 437
 629 981 448 905 435  13 209 405 904 811 368 743  71  29 956 204 623 770
 409 404 144 437 917 967  66 633 834 786 497   0 384 715 788 826 691  44
  91  86 169 978 359 116 998 836 474 372 922 931 432 177 435  72 134 464
 640 410 849 371 503 766 508 185   6 536 610 696 905 914 484 718 902 582
 853  17 372 179 440 767 976  60   5 582 433 976  29 758 918 978 657 832
 876 751 881 134 920 190 455 407 610 643 866 689 15

In [19]:
import hashlib
import time
# 要测量的代码
def sha256_string(input_string):
    # 将字符串编码为 UTF-8 字节
    encoded_string = input_string.encode('utf-8')
    # 创建 SHA-256 哈希对象
    sha256_hash = hashlib.sha256(encoded_string)
    # 获取十六进制格式的哈希值
    return sha256_hash.hexdigest()



 
# 示例
text = "Hello, World!"

start = time.perf_counter()
hashed_text = sha256_string(text)

 
end = time.perf_counter()
elapsed = end - start

print(f"SHA-256 哈希值: {hashed_text}")
# 计算耗时（秒）
print(f"代码执行耗时: {elapsed:.9f} 秒")


SHA-256 哈希值: dffd6021bb2bd5b0af676290809ec3a53191dd81c7f70a4b28688a362182986f
代码执行耗时: 0.000072000 秒


In [20]:
#离散的hash阈值比较方法

import numpy as np
def hashComare(dist,p,q):
    #q=1024*1024  #明文模数
    print("q:")
    print(q)
    threshold=2000
    rightMax=10000
    # 生成 10 个 [0, 10000) 的随机整数
    #dist = np.random.randint(0, 10000, size=10000)
    print("dist:")
    print(dist)
    #p=1
    dimension=dist.shape[0]
    TrueAns=[]
    for i in range(dimension):
        isContains=False
        if (dist[i] > threshold) and (dist[i] <= rightMax):
            isContains=True
        TrueAns.append(isContains)    
    r=genRandom(dimension,999999999)
    print("r:")
    print(r)
    dist=dist+r
    dist=dist//p
    dist=dist%q
    print("((dist+r)/p)%q:")
    print(dist)
    #     print(dist[:5])




    # 生成维度为4000的ndarray，所有值都是constant_value  

    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    thresh=thresh%q
    print("((threshold+r)/p)%q:")
    print(thresh)



    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    rightM=rightM%q
    print("((rightM+r)/p)%q:")
    print(rightM)
    ans=[]
    for i in range(dimension):  # 0 到 4
        #print(i)
        left=thresh[i]
        right=rightM[i]
        sim=dist[i]
        #print(left)
        #print(right)
        #print(sim)
       #转换为字符串（默认）
        str_sim = "{}".format(sim)
        #print(str_sim) 
        simHash=sha256_string(str_sim)
        #print(simHash)
        # 组合两个条件：dist > thresh 且 dist <= rightM
        start = left+1  # 起始数字
        count = (rightMax-threshold)//p  # 往后数 right-left 个数（包括起始数字）
        Hashs=[]
        for i in range(start, start + count):
            num=i%q
            str_num= "{}".format(num)
            SetHash=sha256_string(str_num)
            Hashs.append(SetHash)
            #print(i)
        #print(Hashs)
        isContain=False
        for i in range(count):
            if simHash==Hashs[i]:
                isContain=True
        ans.append(isContain)   
    print(TrueAns)
    print(ans)

    sameCount=0
    diffCount=0
    for i in range(dimension):
        if TrueAns[i]==ans[i]:
            sameCount=sameCount+1
        else:
            diffCount=diffCount+1


    print("相同结果的数量:", sameCount) 

    print("不同结果的数量:", diffCount)  
    return ans

In [21]:
p=100
q=1024*1024
dist = np.random.randint(-10000, 10000, size=1000)
predict_issame=hashComare(dist,p,q)
print(predict_issame)

q:
1048576
dist:
[-5681  4348 -4723  4745 -2801  4298  9302   -32 -8362 -2761 -5672  2174
  9976  5098 -7426 -8249  1945 -6216  9469 -7205 -2489  5081 -1231   556
  -501  3393 -5720  5867   649  9392   567  5843  8305  -937  2206 -1048
   364 -9344 -3167 -4974 -6200 -1782  6135  5125  -218 -8331 -2720  4993
  5458  5884 -2122 -4028  6362  7388  1245  7594 -3498   199  9080  2693
 -1688  -905 -5757  7889 -4616  5196  -949 -7434 -9050 -3719 -8734 -6706
   -56  6447  1200 -1909  1816 -1149  6529 -2110 -2742 -1371 -9808 -6680
  7606 -7593 -1435 -7312 -4459 -8681 -6588 -9426 -7081 -1226 -2969  9499
 -8139 -5414  1404 -9297 -8008   222  9852 -5614 -6916  5537  9963  1762
 -2958 -3250 -3895 -4441 -7042  1198 -4478 -3722  -828 -5914 -8336   910
  8616  3631 -8372 -7269 -5664 -7466 -6367  3426  2926  7310 -6158 -3948
  -938  -680 -1002  8116   470 -6723   530 -6591 -1172  6552 -6319   975
 -9206 -5481 -4171 -5687 -9794  7061 -8820 -2271 -6959 -2127  3325  8525
  5644  1329 -2728 -8363  3227  55

In [32]:
from sklearn.model_selection import KFold
from scipy import interpolate
import math
import numpy as np  
  

all_threshold=[]
# LFW functions taken from David Sandberg's FaceNet implementation
def distance(embeddings1, embeddings2, distance_metric=1):
    if distance_metric==0:
        # Euclidian distance
        diff = np.subtract(embeddings1, embeddings2)
        dist = np.sum(np.square(diff),1)
    elif distance_metric==1:
        # Distance based on cosine similarity
        dot = np.sum(np.multiply(embeddings1, embeddings2), axis=1)
        #norm = np.linalg.norm(embeddings1, axis=1) * np.linalg.norm(embeddings2, axis=1)
        #similarity = dot / norm
        similarity=dot
        #dist = np.arccos(similarity) / math.pi
        dist =similarity
    elif distance_metric==2:
        dist=distances(embeddings1,embeddings2)
    else:
        raise 'Undefined distance metric %d' % distance_metric

    return dist

def calculate_roc(thresholds, embeddings1, embeddings2, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    tprs = np.zeros((nrof_folds,nrof_thresholds))
    fprs = np.zeros((nrof_folds,nrof_thresholds))
    accuracy = np.zeros((nrof_folds))

    is_false_positive = []
    is_false_negative = []

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        # Find the best threshold for the fold
        acc_train = np.zeros((nrof_thresholds))
        for threshold_idx, threshold in enumerate(thresholds):
            _, _, acc_train[threshold_idx], _ ,_ = calculate_accuracy(threshold, dist[train_set], actual_issame[train_set])
        best_threshold_index = np.argmax(acc_train)
        print(thresholds[best_threshold_index])
        all_threshold.append(thresholds[best_threshold_index])
        for threshold_idx, threshold in enumerate(thresholds):
            tprs[fold_idx,threshold_idx], fprs[fold_idx,threshold_idx], _, _, _ = calculate_accuracy(threshold, dist[test_set], actual_issame[test_set])
        _, _, accuracy[fold_idx], is_fp, is_fn = calculate_accuracy(thresholds[best_threshold_index], dist[test_set], actual_issame[test_set])

        tpr = np.mean(tprs,0)
        fpr = np.mean(fprs,0)
        is_false_positive.extend(is_fp)
        is_false_negative.extend(is_fn)

    return tpr, fpr, accuracy, is_false_positive, is_false_negative

def calculate_accuracy(threshold, dist, actual_issame):

    dist = np.round(dist).astype(np.int32) #注意前半部分在同态下算完应该是整数  浮点数转为整数
    q=1024*1024
    p=500
    predict_issame=hashComare(dist,p,q)
    tp = np.sum(np.logical_and(predict_issame, actual_issame))
    fp = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    tn = np.sum(np.logical_and(np.logical_not(predict_issame), np.logical_not(actual_issame)))
    fn = np.sum(np.logical_and(np.logical_not(predict_issame), actual_issame))

    is_fp = np.logical_and(predict_issame, np.logical_not(actual_issame))
    is_fn = np.logical_and(np.logical_not(predict_issame), actual_issame)

    tpr = 0 if (tp+fn==0) else float(tp) / float(tp+fn)
    fpr = 0 if (fp+tn==0) else float(fp) / float(fp+tn)
    acc = float(tp+tn)/dist.size
    #acc = float(tp+tn)/len(dist)
    return tpr, fpr, acc, is_fp, is_fn

def calculate_val(thresholds, embeddings1, embeddings2, actual_issame, far_target, nrof_folds=10, distance_metric=1, subtract_mean=False):
    assert(embeddings1.shape[0] == embeddings2.shape[0])
    assert(embeddings1.shape[1] == embeddings2.shape[1])
    nrof_pairs = min(len(actual_issame), embeddings1.shape[0])
    nrof_thresholds = len(thresholds)
    k_fold = KFold(n_splits=nrof_folds, shuffle=False)

    val = np.zeros(nrof_folds)
    far = np.zeros(nrof_folds)

    indices = np.arange(nrof_pairs)

    for fold_idx, (train_set, test_set) in enumerate(k_fold.split(indices)):
        if subtract_mean:
            mean = np.mean(np.concatenate([embeddings1[train_set], embeddings2[train_set]]), axis=0)
        else:
            mean = 0.0
        #mean=0.0
        dist = distance(embeddings1-mean, embeddings2-mean, distance_metric)

        #Find the threshold that gives FAR = far_target
        far_train = np.zeros(nrof_thresholds)
        for threshold_idx, threshold in enumerate(thresholds):
            _, far_train[threshold_idx] = calculate_val_far(threshold, dist[train_set], actual_issame[train_set])
        if np.max(far_train)>=far_target:
            f = interpolate.interp1d(far_train, thresholds, kind='slinear')
            threshold = f(far_target)
        else:
            threshold = 0.0
       # threshold=4000
     

        val[fold_idx], far[fold_idx] = calculate_val_far(threshold, dist[test_set], actual_issame[test_set])

    val_mean = np.mean(val)
    far_mean = np.mean(far)
    val_std = np.std(val)
    return val_mean, val_std, far_mean

def calculate_val_far(threshold, dist, actual_issame):
    #threshold=0.41
    predict_issame = np.greater(dist, threshold)
    true_accept = np.sum(np.logical_and(predict_issame, actual_issame))
    false_accept = np.sum(np.logical_and(predict_issame, np.logical_not(actual_issame)))
    n_same = np.sum(actual_issame)
    n_diff = np.sum(np.logical_not(actual_issame))
    val = float(true_accept) / float(n_same)
    far = float(false_accept) / float(n_diff)
    return val, far



def evaluate(embeddings, actual_issame, nrof_folds=10, distance_metric=1, subtract_mean=False):
    # Calculate evaluation metrics
    print(embeddings.shape)
    #thresholds = np.arange(-1, 1, 0.01) 
    #thresholds = np.arange(-10000, 10000, 5000) 
    thresholds=[2000]
    #thresholds = np.arange(-40000, 40000, 100) 
    embeddings1 = embeddings[0::2]
    embeddings2 = embeddings[1::2]
    tpr, fpr, accuracy, fp, fn  = calculate_roc(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    #thresholds = np.arange(-10000, 10000, 5000)
    thresholds=[2000]
    #thresholds = np.arange(-1, 1, 0.001)
    #thresholds = np.arange(-40000, 40000,10)
    val, val_std, far = calculate_val(thresholds, embeddings1, embeddings2,
        np.asarray(actual_issame), 1e-2, nrof_folds=nrof_folds, distance_metric=distance_metric, subtract_mean=subtract_mean)
    return tpr, fpr, accuracy, val, val_std, far, fp, fn

def add_extension(path):
#     if os.path.exists(path+'.jpg'):
#         return path+'.jpg'
#     elif os.path.exists(path+'.png'):
#         return path+'.png'
#     else:
#         raise RuntimeError('No file "%s" with extension png or jpg.' % path)
    return path+'.jpg'

def get_paths(lfw_dir, pairs):
    nrof_skipped_pairs = 0
    path_list = []
    issame_list = []
    for pair in pairs:
        if len(pair) == 3:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[2])))
            issame = True
        elif len(pair) == 4:
            path0 = add_extension(os.path.join(lfw_dir, pair[0], pair[0] + '_' + '%04d' % int(pair[1])))
            path1 = add_extension(os.path.join(lfw_dir, pair[2], pair[2] + '_' + '%04d' % int(pair[3])))
            issame = False
        path_list += (path0,path1)
        issame_list.append(issame)
#         if os.path.exists(path0) and os.path.exists(path1):    # Only add the pair if both paths exist
#             path_list += (path0,path1)
#             issame_list.append(issame)
#         else:
#             nrof_skipped_pairs += 1
    if nrof_skipped_pairs>0:
        print('Skipped %d image pairs' % nrof_skipped_pairs)

    return path_list, issame_list

def read_pairs(pairs_filename):
    pairs = []
    with open(pairs_filename, 'r') as f:
        for line in f.readlines()[1:]:
            pair = line.strip().split()
            pairs.append(pair)
    return np.array(pairs, dtype=object)

In [33]:
pairs = read_pairs(pairs_path)
path_list, issame_list = get_paths(data_dir, pairs)
embeddings = np.array([em_dict[path] for path in path_list])

tpr, fpr, accuracy, val, val_std, far, fp, fn = evaluate(embeddings, issame_list)

(12000, 512)
q:
1048576
dist:
[ 918 5620 8747 ...   53  490  500]
r:
[165405775 323445351 566600312 ...  89886475 688860971 469965946]
((dist+r)/p)%q:
[330813 646901  84642 ... 179773 329146 939932]
((threshold+r)/p)%q:
[330815 646894  84628 ... 179776 329149 939935]
((rightM+r)/p)%q:
[330831 646910  84644 ... 179792 329165 939951]
[False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

2000
q:
1048576
dist:
[ 5192  5481  5927  2971  4553  4689  5253  5183  3744  4607  4190  3397
  1598  4653  6274  5892  4896  4531  2727  2902  5226  5248  4058  6584
  7368  3879  4315  3431  4858  3854  4644  5772  7303  6245  3506  4296
  4095  5851  3936  6568  5359  5390  4489  6277  5273  4882  5252  3441
  4975  6571  4975  6044  3355  4431  4334  5179  1983  4341  6267  6183
  5775  4391  3866  5348  3829  4152  6510  4752  5106  5302  4625  5274
  2753  6384  5792  4396  5566  6362  5023  5520  6016  4891  3948  6651
  5336  4447  3377  5294  7618  4660  4050  5109  6924  5518  5191  5062
  5530  2999  5630  6921  5787  6578  4467  6180  5417  4357   677  3704
  6061  5989  5093  5563  5326  4465  5497  6456  1561  5092  5223  5097
  6121  4599  4138  4718  2541   732  4850  4046  5621  6058  3732  6656
  6461  5056  5566  5209   958  6396  4360  4226  5521  7606  4496  3489
  5619  2717  4121  3718  7077  6110  4169  2050  7811  5144  4992  4822
  5966  6999  7045  6446  509

2000
q:
1048576
dist:
[ 5695  7853  5538  5822  6380  5151  4758  5390  2981  6543  4249  3388
  6116  4927  4975  6841  4280  3990  5579  6386  5582  5447  7955  5336
  4052  4676  4894  5400  5566  3949  4703  4570  2171  3013  3096  3444
  2243  6200  7121  4665  4260  6399  7466  5472  5313  6262  4154  3963
  5602  5436  3714  5865  4767  6346  6129  5872  5773  4404  4939  7768
  3749  2721  2069  4812  4876  6360  4971   640  5385  3956  5283  8477
  5438  3705  5256  5028  6385  4448  6761  4244  6176  5016  4936  6390
  2785  6309  6029  5180  5434  7664  4824  3943  5805  5516   980  4997
  5134  5302  6862  4640  5221  3737  6356  2597  4323  5399  2630  5601
  6348  5535  3180  5158  4804  4958  6124  4568  4591  7151  5151  4333
  6720  3107  5251  5607  6763  4786  5440  4348  6143  1731  5315  5775
  5243  5553  7471  5006  3798  5710  7169  4672  6803  7030  3899  5102
  6847  7526  1374  3620  4577  5615  6072  3610  6411  6612  6264  5997
  4219  5588  4066  5514  164

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

[True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, 

In [34]:
print(accuracy)
np.mean(accuracy)





[0.985      0.97166667 0.97333333 0.98333333 0.97166667 0.97666667
 0.97166667 0.97666667 0.98       0.975     ]


0.9764999999999999

In [33]:
np.mean(all_threshold)


2310.0

In [92]:
print(len(pairs))

6000


In [1025]:
    #a little test for look the error situation
    dist = np.array([2100,2200.2299,2500, 3000, 4000,5000,9000,10000])
    p=1000
    dimension=dist.shape[0]
    r=genRandom(dimension,99999999)
    print(r)
    dist=dist+r
    dist=dist//p
    print(dist)

    # 生成维度为4000的ndarray，所有值都是constant_value  
    threshold=2300
    thresh = np.full(dimension, threshold)  
    thresh=thresh+r
    thresh=thresh//p
    print(thresh)

    rightMax=10000
    rightM= np.full(dimension, rightMax)  
    rightM=rightM+r
    rightM=rightM//p
    print(rightM)

    # 组合两个条件：dist > thresh 且 dist <= rightM
    predict_issame = (dist > thresh) & (dist <= rightM)
    print(predict_issame)

[55633634 45308601 12542928 70346752  9871909 11995441 77442695 64250201]
[55635. 45310. 12545. 70349.  9875. 12000. 77451. 64260.]
[55635 45310 12545 70349  9874 11997 77444 64252]
[55643 45318 12552 70356  9881 12005 77452 64260]
[False False False False  True  True  True  True]
